package singleplayer

import (
	"github.com/deosjr/PokemonGo/src/model"
)

type rentalPokemon struct {
	species string
	moves   [4]string
	ability string
	item    string
}

func GetRentalPokemon() *model.Pokemon {
	rental := rentals[random.Intn(len(rentals))]
	p := model.GetPokemonByName(100, rental.species)
	for i := 0; i < 4; i++ {
		move, ok := model.GetMoveByName(rental.moves[i])
		if !ok {
			panic(rental.moves[i])
		}
		p.Moves[i] = move
	}
	return p
}

var rentals []rentalPokemon = []rentalPokemon{
	{
		ability: "Overgrow",
		item:    "White Herb",
		species: "Venusaur",
		moves: [4]string{"Leaf Storm",
			"Sludge Bomb",
			"Amnesia",
			"Sleep Powder",
		}}, {
		ability: "Overgrow",
		item:    "Big Root",
		species: "Venusaur",
		moves: [4]string{"Giga Drain",
			"Ingrain",
			"Leech Seed",
			"Sleep Powder",
		}}, {
		ability: "Overgrow",
		item:    "Black Sludge",
		species: "Venusaur",
		moves: [4]string{"Seed Bomb",
			"Earthquake",
			"Outrage",
			"Curse",
		}}, {
		ability: "Overgrow",
		item:    "Wise Glasses",
		species: "Venusaur",
		moves: [4]string{"Frenzy Plant",
			"Sludge Bomb",
			"Hyper Beam",
			"Synthesis",
		}}, {
		ability: "Blaze",
		item:    "Petaya Berry",
		species: "Charizard",
		moves: [4]string{"Flamethrower",
			"Air Slash",
			"SmokeScreen",
			"Scary Face",
		}}, {
		ability: "Blaze",
		item:    "White Herb",
		species: "Charizard",
		moves: [4]string{"Overheat",
			"Solar Beam",
			"Will-O-Wisp",
			"Sunny Day",
		}}, {
		ability: "Blaze",
		item:    "Scope Lens",
		species: "Charizard",
		moves: [4]string{"Flare Blitz",
			"Earthquake",
			"Crunch",
			"Dragon Claw",
		}}, {
		ability: "Blaze",
		item:    "Bright Powder",
		species: "Charizard",
		moves: [4]string{"Blast Burn",
			"Air Slash",
			"Focus Blast",
			"Ancient Power",
		}}, {
		ability: "Torrent",
		item:    "Mystic Water",
		species: "Blastoise",
		moves: [4]string{"Hydro Pump",
			"Signal Beam",
			"Icy Wind",
			"Mirror Coat",
		}}, {
		ability: "Torrent",
		item:    "Shell Bell",
		species: "Blastoise",
		moves: [4]string{"Waterfall",
			"Focus Punch",
			"Double Team",
			"Aqua Ring",
		}}, {
		ability: "Torrent",
		item:    "Life Orb",
		species: "Blastoise",
		moves: [4]string{"Aqua Tail",
			"Earthquake",
			"Avalanche",
			"Zen Headbutt",
		}}, {
		ability: "Torrent",
		item:    "Shell Bell",
		species: "Blastoise",
		moves: [4]string{"Hydro Cannon",
			"Ice Beam",
			"Hyper Beam",
			"Focus Blast",
		}}, {
		ability: "Static",
		item:    "Wide Lens",
		species: "Raichu",
		moves: [4]string{"Thunder Punch",
			"Iron Tail",
			"Slam",
			"Quick Attack",
		}}, {
		ability: "Static",
		item:    "Focus Band",
		species: "Raichu",
		moves: [4]string{"Thunder Punch",
			"Focus Punch",
			"Sweet Kiss",
			"Thunder Wave",
		}}, {
		ability: "Static",
		item:    "Petaya Berry",
		species: "Raichu",
		moves: [4]string{"Thunderbolt",
			"Focus Blast",
			"Signal Beam",
			"Nasty Plot",
		}}, {
		ability: "Static",
		item:    "Bright Powder",
		species: "Raichu",
		moves: [4]string{"Volt Tackle",
			"Return",
			"Brick Break",
			"Thunder Wave",
		}}, {
		ability: "Rivalry",
		item:    "Payapa Berry",
		species: "Nidoqueen",
		moves: [4]string{"Earthquake",
			"Poison Fang",
			"Aerial Ace",
			"Charm",
		}}, {
		ability: "Rivalry",
		item:    "Scope Lens",
		species: "Nidoqueen",
		moves: [4]string{"Poison Jab",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Rivalry",
		item:    "Black Sludge",
		species: "Nidoqueen",
		moves: [4]string{"Sludge Bomb",
			"Earth Power",
			"Flamethrower",
			"Ice Beam",
		}}, {
		ability: "Rivalry",
		item:    "Razor Claw",
		species: "Nidoqueen",
		moves: [4]string{"Earthquake",
			"Poison Jab",
			"Superpower",
			"Crunch",
		}}, {
		ability: "Rivalry",
		item:    "Focus Band",
		species: "Nidoking",
		moves: [4]string{"Earthquake",
			"Poison Jab",
			"Double Kick",
			"Counter",
		}}, {
		ability: "Rivalry",
		item:    "Bright Powder",
		species: "Nidoking",
		moves: [4]string{"Focus Punch",
			"Dragon Pulse",
			"Horn Drill",
			"Substitute",
		}}, {
		ability: "Rivalry",
		item:    "Expert Belt",
		species: "Nidoking",
		moves: [4]string{"Earth Power",
			"Sludge Bomb",
			"Ice Beam",
			"Shadow Ball",
		}}, {
		ability: "Rivalry",
		item:    "Muscle Band",
		species: "Nidoking",
		moves: [4]string{"Earthquake",
			"Poison Jab",
			"Megahorn",
			"Outrage",
		}}, {
		ability: "Flash Fire",
		item:    "Bright Powder",
		species: "Ninetales",
		moves: [4]string{"Fire Blast",
			"Solar Beam",
			"Attract",
			"Sunny Day",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Ninetales",
		moves: [4]string{"Overheat",
			"Dark Pulse",
			"Nasty Plot",
			"Confuse Ray",
		}}, {
		ability: "Flash Fire",
		item:    "Wide Lens",
		species: "Ninetales",
		moves: [4]string{"Heat Wave",
			"Ominous Wind",
			"Dream Eater",
			"Hypnosis",
		}}, {
		ability: "Flash Fire",
		item:    "Passho Berry",
		species: "Ninetales",
		moves: [4]string{"Flamethrower",
			"Extrasensory",
			"Energy Ball",
			"Calm Mind",
		}}, {
		ability: "Chlorophyll",
		item:    "Big Root",
		species: "Vileplume",
		moves: [4]string{"Giga Drain",
			"Sludge Bomb",
			"Sleep Powder",
			"Ingrain",
		}}, {
		ability: "Chlorophyll",
		item:    "Black Sludge",
		species: "Vileplume",
		moves: [4]string{"Toxic",
			"Grass Knot",
			"Double Team",
			"Attract",
		}}, {
		ability: "Chlorophyll",
		item:    "Lum Berry",
		species: "Vileplume",
		moves: [4]string{"Seed Bomb",
			"Drain Punch",
			"Frustration",
			"Swords Dance",
		}}, {
		ability: "Chlorophyll",
		item:    "Wise Glasses",
		species: "Vileplume",
		moves: [4]string{"Sludge Bomb",
			"Energy Ball",
			"Hyper Beam",
			"Synthesis",
		}}, {
		ability: "Arena Trap",
		item:    "Grip Claw",
		species: "Dugtrio",
		moves: [4]string{"Earthquake",
			"Rock Slide",
			"Astonish",
			"Sand Tomb",
		}}, {
		ability: "Arena Trap",
		item:    "Lax Incense",
		species: "Dugtrio",
		moves: [4]string{"Earth Power",
			"Sludge Bomb",
			"Tri Attack",
			"Sandstorm",
		}}, {
		ability: "Arena Trap",
		item:    "Razor Claw",
		species: "Dugtrio",
		moves: [4]string{"Fissure",
			"Giga Impact",
			"Aerial Ace",
			"Night Slash",
		}}, {
		ability: "Arena Trap",
		item:    "Muscle Band",
		species: "Dugtrio",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Slash",
			"Shadow Claw",
		}}, {
		ability: "Cloud Nine",
		item:    "Rindo Berry",
		species: "Golduck",
		moves: [4]string{"Surf",
			"Psychic",
			"Confuse Ray",
			"Calm Mind",
		}}, {
		ability: "Cloud Nine",
		item:    "Shell Bell",
		species: "Golduck",
		moves: [4]string{"Waterfall",
			"Mud Bomb",
			"Shadow Claw",
			"Aerial Ace",
		}}, {
		ability: "Cloud Nine",
		item:    "Scope Lens",
		species: "Golduck",
		moves: [4]string{"Aqua Tail",
			"Cross Chop",
			"Ice Punch",
			"Zen Headbutt",
		}}, {
		ability: "Cloud Nine",
		item:    "Wacan Berry",
		species: "Golduck",
		moves: [4]string{"Hydro Pump",
			"Psychic",
			"Ice Beam",
			"Signal Beam",
		}}, {
		ability: "Flash Fire",
		item:    "Lum Berry",
		species: "Arcanine",
		moves: [4]string{"Fire Fang",
			"Extreme Speed",
			"Crunch",
			"Will-O-Wisp",
		}}, {
		ability: "Flash Fire",
		item:    "Salac Berry",
		species: "Arcanine",
		moves: [4]string{"Flare Blitz",
			"Thunder Fang",
			"Reversal",
			"Endure",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Arcanine",
		moves: [4]string{"Overheat",
			"Solar Beam",
			"Dragon Pulse",
			"Sunny Day",
		}}, {
		ability: "Flash Fire",
		item:    "Focus Band",
		species: "Arcanine",
		moves: [4]string{"Flare Blitz",
			"Extreme Speed",
			"Crunch",
			"Thunder Fang",
		}}, {
		ability: "Damp",
		item:    "Rindo Berry",
		species: "Poliwrath",
		moves: [4]string{"Surf",
			"Vacuum Wave",
			"Psychic",
			"Double Team",
		}}, {
		ability: "Damp",
		item:    "Lax Incense",
		species: "Poliwrath",
		moves: [4]string{"Waterfall",
			"Dynamic Punch",
			"Poison Jab",
			"Bulk Up",
		}}, {
		ability: "Damp",
		item:    "Wide Lens",
		species: "Poliwrath",
		moves: [4]string{"Hydro Pump",
			"Focus Blast",
			"Blizzard",
			"Mud Bomb",
		}}, {
		ability: "Damp",
		item:    "Expert Belt",
		species: "Poliwrath",
		moves: [4]string{"Waterfall",
			"Focus Punch",
			"Earthquake",
			"Hypnosis",
		}}, {
		ability: "Inner Focus",
		item:    "Bright Powder",
		species: "Alakazam",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Calm Mind",
			"Future Sight",
		}}, {
		ability: "Inner Focus",
		item:    "Colbur Berry",
		species: "Alakazam",
		moves: [4]string{"Psychic",
			"Focus Blast",
			"Charge Beam",
			"Recover",
		}}, {
		ability: "Inner Focus",
		item:    "Wise Glasses",
		species: "Alakazam",
		moves: [4]string{"Psychic",
			"Charge Beam",
			"Signal Beam",
			"Grass Knot",
		}}, {
		ability: "Inner Focus",
		item:    "Expert Belt",
		species: "Alakazam",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Energy Ball",
			"Focus Blast",
		}}, {
		ability: "No Guard",
		item:    "Scope Lens",
		species: "Machamp",
		moves: [4]string{"Cross Chop",
			"Earthquake",
			"Bullet Punch",
			"Foresight",
		}}, {
		ability: "No Guard",
		item:    "Focus Sash",
		species: "Machamp",
		moves: [4]string{"Revenge",
			"Earthquake",
			"Payback",
			"Counter",
		}}, {
		ability: "No Guard",
		item:    "Quick Claw",
		species: "Machamp",
		moves: [4]string{"Dynamic Punch",
			"Earthquake",
			"Stone Edge",
			"Ice Punch",
		}}, {
		ability: "No Guard",
		item:    "Quick Claw",
		species: "Machamp",
		moves: [4]string{"Cross Chop",
			"Earthquake",
			"Thunder Punch",
			"Fire Punch",
		}}, {
		ability: "Chlorophyll",
		item:    "Payapa Berry",
		species: "Victreebel",
		moves: [4]string{"Leaf Storm",
			"Sludge Bomb",
			"Sleep Powder",
			"Gastro Acid",
		}}, {
		ability: "Chlorophyll",
		item:    "Black Sludge",
		species: "Victreebel",
		moves: [4]string{"Seed Bomb",
			"Spit Up",
			"Swallow",
			"Stockpile",
		}}, {
		ability: "Chlorophyll",
		item:    "Power Herb",
		species: "Victreebel",
		moves: [4]string{"Sludge Bomb",
			"Solar Beam",
			"Hyper Beam",
			"Synthesis",
		}}, {
		ability: "Chlorophyll",
		item:    "Focus Band",
		species: "Victreebel",
		moves: [4]string{"Solar Beam",
			"Sludge Bomb",
			"Wring Out",
			"Sunny Day",
		}}, {
		ability: "Liquid Ooze",
		item:    "Wacan Berry",
		species: "Tentacruel",
		moves: [4]string{"Surf",
			"Sludge Bomb",
			"Icy Wind",
			"Barrier",
		}}, {
		ability: "Liquid Ooze",
		item:    "Black Sludge",
		species: "Tentacruel",
		moves: [4]string{"Toxic",
			"Giga Drain",
			"Attract",
			"Confuse Ray",
		}}, {
		ability: "Liquid Ooze",
		item:    "Focus Sash",
		species: "Tentacruel",
		moves: [4]string{"Surf",
			"Sludge Bomb",
			"Giga Drain",
			"Mirror Coat",
		}}, {
		ability: "Liquid Ooze",
		item:    "Scope Lens",
		species: "Tentacruel",
		moves: [4]string{"Hydro Pump",
			"Sludge Bomb",
			"Ice Beam",
			"Wring Out",
		}}, {
		ability: "Sturdy",
		item:    "Focus Band",
		species: "Golem",
		moves: [4]string{"Earthquake",
			"Rock Slide",
			"Sucker Punch",
			"Sandstorm",
		}}, {
		ability: "Sturdy",
		item:    "White Herb",
		species: "Golem",
		moves: [4]string{"Earthquake",
			"Superpower",
			"Fire Punch",
			"Thunder Punch",
		}}, {
		ability: "Sturdy",
		item:    "Iron Ball",
		species: "Golem",
		moves: [4]string{"Gyro Ball",
			"Earthquake",
			"Hammer Arm",
			"Fling",
		}}, {
		ability: "Sturdy",
		item:    "Quick Claw",
		species: "Golem",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Gyro Ball",
			"Explosion",
		}}, {
		ability: "Flash Fire",
		item:    "Chesto Berry",
		species: "Rapidash",
		moves: [4]string{"Fire Blast",
			"Solar Beam",
			"Sunny Day",
			"Rest",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Rapidash",
		moves: [4]string{"Overheat",
			"Solar Beam",
			"Swift",
			"Sunny Day",
		}}, {
		ability: "Flash Fire",
		item:    "Bright Powder",
		species: "Rapidash",
		moves: [4]string{"Flare Blitz",
			"Poison Jab",
			"Iron Tail",
			"Horn Drill",
		}}, {
		ability: "Flash Fire",
		item:    "Chesto Berry",
		species: "Rapidash",
		moves: [4]string{"Flare Blitz",
			"Megahorn",
			"Double-Edge",
			"Hypnosis",
		}}, {
		ability: "Own Tempo",
		item:    "Chesto Berry",
		species: "Slowbro",
		moves: [4]string{"Psychic",
			"Surf",
			"Calm Mind",
			"Yawn",
		}}, {
		ability: "Own Tempo",
		item:    "Expert Belt",
		species: "Slowbro",
		moves: [4]string{"Zen Headbutt",
			"Aqua Tail",
			"Earthquake",
			"Avalanche",
		}}, {
		ability: "Own Tempo",
		item:    "Choice Specs",
		species: "Slowbro",
		moves: [4]string{"Psychic",
			"Flamethrower",
			"Shadow Ball",
			"Signal Beam",
		}}, {
		ability: "Own Tempo",
		item:    "Leftovers",
		species: "Slowbro",
		moves: [4]string{"Psychic",
			"Surf",
			"Ice Beam",
			"Trick Room",
		}}, {
		ability: "Hydration",
		item:    "Razor Fang",
		species: "Dewgong",
		moves: [4]string{"Waterfall",
			"Avalanche",
			"Headbutt",
			"Fake Out",
		}}, {
		ability: "Hydration",
		item:    "Wacan Berry",
		species: "Dewgong",
		moves: [4]string{"Ice Beam",
			"Signal Beam",
			"Encore",
			"Disable",
		}}, {
		ability: "Hydration",
		item:    "Salac Berry",
		species: "Dewgong",
		moves: [4]string{"Sheer Cold",
			"Horn Drill",
			"Rest",
			"Sleep Talk",
		}}, {
		ability: "Hydration",
		item:    "Chesto Berry",
		species: "Dewgong",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Signal Beam",
			"Rest",
		}}, {
		ability: "Sticky Hold",
		item:    "Black Sludge",
		species: "Muk",
		moves: [4]string{"Poison Jab",
			"Shadow Sneak",
			"Minimize",
			"Acid Armor",
		}}, {
		ability: "Sticky Hold",
		item:    "Expert Belt",
		species: "Muk",
		moves: [4]string{"Poison Jab",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Sticky Hold",
		item:    "Zoom Lens",
		species: "Muk",
		moves: [4]string{"Gunk Shot",
			"Payback",
			"Shadow Sneak",
			"Curse",
		}}, {
		ability: "Sticky Hold",
		item:    "Quick Claw",
		species: "Muk",
		moves: [4]string{"Gunk Shot",
			"Shadow Sneak",
			"Brick Break",
			"Explosion",
		}}, {
		ability: "Levitate",
		item:    "Payapa Berry",
		species: "Gengar",
		moves: [4]string{"Shadow Ball",
			"Sludge Bomb",
			"Spite",
			"Confuse Ray",
		}}, {
		ability: "Levitate",
		item:    "Life Orb",
		species: "Gengar",
		moves: [4]string{"Shadow Ball",
			"Dream Eater",
			"Hypnosis",
			"Substitute",
		}}, {
		ability: "Levitate",
		item:    "Scope Lens",
		species: "Gengar",
		moves: [4]string{"Psychic",
			"Energy Ball",
			"Focus Blast",
			"Confuse Ray",
		}}, {
		ability: "Levitate",
		item:    "Lum Berry",
		species: "Gengar",
		moves: [4]string{"Shadow Ball",
			"Sludge Bomb",
			"Thunderbolt",
			"Destiny Bond",
		}}, {
		ability: "Forewarn",
		item:    "Iron Ball",
		species: "Hypno",
		moves: [4]string{"Psycho Cut",
			"Fling",
			"Hypnosis",
			"Trick Room",
		}}, {
		ability: "Forewarn",
		item:    "Persim Berry",
		species: "Hypno",
		moves: [4]string{"Dream Eater",
			"Nightmare",
			"Drain Punch",
			"Hypnosis",
		}}, {
		ability: "Forewarn",
		item:    "Sitrus Berry",
		species: "Hypno",
		moves: [4]string{"Zen Headbutt",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Forewarn",
		item:    "Choice Specs",
		species: "Hypno",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Signal Beam",
			"Focus Blast",
		}}, {
		ability: "Static",
		item:    "Chesto Berry",
		species: "Electrode",
		moves: [4]string{"Thunderbolt",
			"Swift",
			"Thunder Wave",
			"Light Screen",
		}}, {
		ability: "Static",
		item:    "Bright Powder",
		species: "Electrode",
		moves: [4]string{"Charge Beam",
			"Thunder Wave",
			"Flash",
			"Swagger",
		}}, {
		ability: "Static",
		item:    "Damp Rock",
		species: "Electrode",
		moves: [4]string{"Thunder",
			"Hyper Beam",
			"Magnet Rise",
			"Rain Dance",
		}}, {
		ability: "Static",
		item:    "Focus Sash",
		species: "Electrode",
		moves: [4]string{"Thunderbolt",
			"Signal Beam",
			"Explosion",
			"Mirror Coat",
		}}, {
		ability: "Chlorophyll",
		item:    "Bright Powder",
		species: "Exeggutor",
		moves: [4]string{"Solar Beam",
			"Psychic",
			"Synthesis",
			"Sunny Day",
		}}, {
		ability: "Chlorophyll",
		item:    "Lum Berry",
		species: "Exeggutor",
		moves: [4]string{"Dream Eater",
			"Hypnosis",
			"Leech Seed",
			"Ingrain",
		}}, {
		ability: "Chlorophyll",
		item:    "Focus Sash",
		species: "Exeggutor",
		moves: [4]string{"Wood Hammer",
			"Zen Headbutt",
			"Trick Room",
			"Explosion",
		}}, {
		ability: "Chlorophyll",
		item:    "Expert Belt",
		species: "Exeggutor",
		moves: [4]string{"Leaf Storm",
			"Psychic",
			"Sludge Bomb",
			"Ancient Power",
		}}, {
		ability: "Lightning Rod",
		item:    "Razor Claw",
		species: "Marowak",
		moves: [4]string{"Bone Rush",
			"Brick Break",
			"Iron Tail",
			"Sandstorm",
		}}, {
		ability: "Lightning Rod",
		item:    "Thick Club",
		species: "Marowak",
		moves: [4]string{"Bone Rush",
			"Fire Punch",
			"Thunder Punch",
			"Rock Slide",
		}}, {
		ability: "Lightning Rod",
		item:    "Thick Club",
		species: "Marowak",
		moves: [4]string{"Earthquake",
			"Giga Impact",
			"Outrage",
			"Fire Punch",
		}}, {
		ability: "Lightning Rod",
		item:    "Thick Club",
		species: "Marowak",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Iron Head",
			"Thunder Punch",
		}}, {
		ability: "Levitate",
		item:    "Payapa Berry",
		species: "Weezing",
		moves: [4]string{"Sludge Bomb",
			"Dark Pulse",
			"Shock Wave",
			"Grudge",
		}}, {
		ability: "Levitate",
		item:    "Sitrus Berry",
		species: "Weezing",
		moves: [4]string{"Double Hit",
			"Payback",
			"Toxic",
			"Swagger",
		}}, {
		ability: "Levitate",
		item:    "Lax Incense",
		species: "Weezing",
		moves: [4]string{"Sludge Bomb",
			"Thunderbolt",
			"Dark Pulse",
			"Explosion",
		}}, {
		ability: "Levitate",
		item:    "Quick Claw",
		species: "Weezing",
		moves: [4]string{"Sludge Bomb",
			"Flamethrower",
			"Shadow Ball",
			"Destiny Bond",
		}}, {
		ability: "Rock Head",
		item:    "Passho Berry",
		species: "Rhydon",
		moves: [4]string{"Earthquake",
			"Rock Slide",
			"Crunch",
			"Scary Face",
		}}, {
		ability: "Rock Head",
		item:    "Focus Sash",
		species: "Rhydon",
		moves: [4]string{"Earthquake",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Rock Head",
		item:    "Persim Berry",
		species: "Rhydon",
		moves: [4]string{"Outrage",
			"Hammer Arm",
			"Shadow Claw",
			"Avalanche",
		}}, {
		ability: "Rock Head",
		item:    "Quick Claw",
		species: "Rhydon",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Megahorn",
			"Horn Drill",
		}}, {
		ability: "Scrappy",
		item:    "Salac Berry",
		species: "Kangaskhan",
		moves: [4]string{"Double-Edge",
			"Crunch",
			"Reversal",
			"Endure",
		}}, {
		ability: "Scrappy",
		item:    "Razor Claw",
		species: "Kangaskhan",
		moves: [4]string{"Dizzy Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Scrappy",
		item:    "Life Orb",
		species: "Kangaskhan",
		moves: [4]string{"Double Hit",
			"Hammer Arm",
			"Shadow Claw",
			"Rock Slide",
		}}, {
		ability: "Scrappy",
		item:    "Muscle Band",
		species: "Kangaskhan",
		moves: [4]string{"Giga Impact",
			"Earthquake",
			"Crunch",
			"Outrage",
		}}, {
		ability: "Natural Cure",
		item:    "Lum Berry",
		species: "Starmie",
		moves: [4]string{"Surf",
			"Psychic",
			"Confuse Ray",
			"Thunder Wave",
		}}, {
		ability: "Natural Cure",
		item:    "Wide Lens",
		species: "Starmie",
		moves: [4]string{"Hydro Pump",
			"Blizzard",
			"Thunder",
			"Recover",
		}}, {
		ability: "Natural Cure",
		item:    "Wise Glasses",
		species: "Starmie",
		moves: [4]string{"Surf",
			"Psychic",
			"Power Gem",
			"Signal Beam",
		}}, {
		ability: "Natural Cure",
		item:    "Expert Belt",
		species: "Starmie",
		moves: [4]string{"Surf",
			"Psychic",
			"Thunderbolt",
			"Ice Beam",
		}}, {
		ability: "Filter",
		item:    "Cheri Berry",
		species: "MrMime",
		moves: [4]string{"Psychic",
			"Signal Beam",
			"Copycat",
			"Mimic",
		}}, {
		ability: "Filter",
		item:    "Light Clay",
		species: "MrMime",
		moves: [4]string{"Dream Eater",
			"Hypnosis",
			"Light Screen",
			"Reflect",
		}}, {
		ability: "Filter",
		item:    "Kasib Berry",
		species: "MrMime",
		moves: [4]string{"Psychic",
			"Thunderbolt",
			"Energy Ball",
			"Hyper Beam",
		}}, {
		ability: "Filter",
		item:    "Choice Specs",
		species: "MrMime",
		moves: [4]string{"Psychic",
			"Charge Beam",
			"Shadow Ball",
			"Focus Blast",
		}}, {
		ability: "Forewarn",
		item:    "Chesto Berry",
		species: "Jynx",
		moves: [4]string{"Psychic",
			"Ice Beam",
			"Lovely Kiss",
			"Fake Tears",
		}}, {
		ability: "Forewarn",
		item:    "Lax Incense",
		species: "Jynx",
		moves: [4]string{"Dream Eater",
			"Lovely Kiss",
			"Perish Song",
			"Mean Look",
		}}, {
		ability: "Forewarn",
		item:    "Expert Belt",
		species: "Jynx",
		moves: [4]string{"Blizzard",
			"Energy Ball",
			"Signal Beam",
			"Wring Out",
		}}, {
		ability: "Forewarn",
		item:    "Choice Specs",
		species: "Jynx",
		moves: [4]string{"Ice Beam",
			"Psychic",
			"Focus Blast",
			"Shadow Ball",
		}}, {
		ability: "Mold Breaker",
		item:    "Coba Berry",
		species: "Pinsir",
		moves: [4]string{"X-Scissor",
			"Earthquake",
			"Rock Slide",
			"Swords Dance",
		}}, {
		ability: "Mold Breaker",
		item:    "Salac Berry",
		species: "Pinsir",
		moves: [4]string{"X-Scissor",
			"Revenge",
			"Flail",
			"Endure",
		}}, {
		ability: "Mold Breaker",
		item:    "Lax Incense",
		species: "Pinsir",
		moves: [4]string{"X-Scissor",
			"Superpower",
			"Stone Edge",
			"Giga Impact",
		}}, {
		ability: "Mold Breaker",
		item:    "Scope Lens",
		species: "Pinsir",
		moves: [4]string{"X-Scissor",
			"Earthquake",
			"Close Combat",
			"Guillotine",
		}}, {
		ability: "Anger Point",
		item:    "Persim Berry",
		species: "Tauros",
		moves: [4]string{"Thrash",
			"Zen Headbutt",
			"Pursuit",
			"Scary Face",
		}}, {
		ability: "Anger Point",
		item:    "Life Orb",
		species: "Tauros",
		moves: [4]string{"Facade",
			"Earthquake",
			"Rock Slide",
			"Payback",
		}}, {
		ability: "Anger Point",
		item:    "Lum Berry",
		species: "Tauros",
		moves: [4]string{"Giga Impact",
			"Earthquake",
			"Outrage",
			"Iron Tail",
		}}, {
		ability: "Anger Point",
		item:    "Choice Band",
		species: "Tauros",
		moves: [4]string{"Return",
			"Earthquake",
			"Stone Edge",
			"Zen Headbutt",
		}}, {
		ability: "Intimidate",
		item:    "Razor Fang",
		species: "Gyarados",
		moves: [4]string{"Aqua Tail",
			"Ice Fang",
			"Bite",
			"Rain Dance",
		}}, {
		ability: "Intimidate",
		item:    "Lum Berry",
		species: "Gyarados",
		moves: [4]string{"Waterfall",
			"Ice Fang",
			"Iron Head",
			"Dragon Dance",
		}}, {
		ability: "Intimidate",
		item:    "Persim Berry",
		species: "Gyarados",
		moves: [4]string{"Outrage",
			"Waterfall",
			"Stone Edge",
			"Giga Impact",
		}}, {
		ability: "Intimidate",
		item:    "Chesto Berry",
		species: "Gyarados",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Rest",
			"Dragon Dance",
		}}, {
		ability: "Shell Armor",
		item:    "Leftovers",
		species: "Lapras",
		moves: [4]string{"Aqua Tail",
			"Avalanche",
			"Ice Shard",
			"Curse",
		}}, {
		ability: "Shell Armor",
		item:    "Quick Claw",
		species: "Lapras",
		moves: [4]string{"Sheer Cold",
			"Perish Song",
			"Sing",
			"Confuse Ray",
		}}, {
		ability: "Shell Armor",
		item:    "Lum Berry",
		species: "Lapras",
		moves: [4]string{"Waterfall",
			"Outrage",
			"Zen Headbutt",
			"Dragon Dance",
		}}, {
		ability: "Shell Armor",
		item:    "Bright Powder",
		species: "Lapras",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Psychic",
			"Thunderbolt",
		}}, {
		ability: "Water Absorb",
		item:    "Bright Powder",
		species: "Vaporeon",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Acid Armor",
			"Baton Pass",
		}}, {
		ability: "Water Absorb",
		item:    "Damp Rock",
		species: "Vaporeon",
		moves: [4]string{"Hydro Pump",
			"Ice Beam",
			"Acid Armor",
			"Rain Dance",
		}}, {
		ability: "Water Absorb",
		item:    "Leftovers",
		species: "Vaporeon",
		moves: [4]string{"Muddy Water",
			"Blizzard",
			"Aqua Ring",
			"Yawn",
		}}, {
		ability: "Water Absorb",
		item:    "Expert Belt",
		species: "Vaporeon",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Shadow Ball",
			"Signal Beam",
		}}, {
		ability: "Volt Absorb",
		item:    "Focus Sash",
		species: "Jolteon",
		moves: [4]string{"Thunderbolt",
			"Thunder Wave",
			"Agility",
			"Baton Pass",
		}}, {
		ability: "Volt Absorb",
		item:    "Razor Claw",
		species: "Jolteon",
		moves: [4]string{"Discharge",
			"Double Kick",
			"Dig",
			"Thunder Wave",
		}}, {
		ability: "Volt Absorb",
		item:    "Lax Incense",
		species: "Jolteon",
		moves: [4]string{"Thunder",
			"Shadow Ball",
			"Rain Dance",
			"Yawn",
		}}, {
		ability: "Volt Absorb",
		item:    "Razor Fang",
		species: "Jolteon",
		moves: [4]string{"Thunderbolt",
			"Hyper Beam",
			"Shadow Ball",
			"Signal Beam",
		}}, {
		ability: "Flash Fire",
		item:    "Quick Claw",
		species: "Flareon",
		moves: [4]string{"Fire Fang",
			"Superpower",
			"Curse",
			"Baton Pass",
		}}, {
		ability: "Flash Fire",
		item:    "Salac Berry",
		species: "Flareon",
		moves: [4]string{"Fire Fang",
			"Flail",
			"Endure",
			"Sand-Attack",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Flareon",
		moves: [4]string{"Overheat",
			"Shadow Ball",
			"Mud-Slap",
			"Will-O-Wisp",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Flareon",
		moves: [4]string{"Fire Fang",
			"Giga Impact",
			"Superpower",
			"Bite",
		}}, {
		ability: "Pressure",
		item:    "King's Rock",
		species: "Aerodactyl",
		moves: [4]string{"Rock Slide",
			"Aerial Ace",
			"Torment",
			"Taunt",
		}}, {
		ability: "Pressure",
		item:    "Razor Fang",
		species: "Aerodactyl",
		moves: [4]string{"Bite",
			"Fire Fang",
			"Thunder Fang",
			"Ice Fang",
		}}, {
		ability: "Pressure",
		item:    "Yache Berry",
		species: "Aerodactyl",
		moves: [4]string{"Giga Impact",
			"Earthquake",
			"Rock Slide",
			"Crunch",
		}}, {
		ability: "Pressure",
		item:    "Choice Band",
		species: "Aerodactyl",
		moves: [4]string{"Stone Edge",
			"Aerial Ace",
			"Earthquake",
			"Dragon Claw",
		}}, {
		ability: "Thick Fat",
		item:    "Leftovers",
		species: "Snorlax",
		moves: [4]string{"Return",
			"Rock Slide",
			"Curse",
			"Yawn",
		}}, {
		ability: "Thick Fat",
		item:    "Chesto Berry",
		species: "Snorlax",
		moves: [4]string{"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
			"Rest",
		}}, {
		ability: "Thick Fat",
		item:    "White Herb",
		species: "Snorlax",
		moves: [4]string{"Outrage",
			"Superpower",
			"Gunk Shot",
			"Seed Bomb",
		}}, {
		ability: "Thick Fat",
		item:    "Life Orb",
		species: "Snorlax",
		moves: [4]string{"Double-Edge",
			"Earthquake",
			"Zen Headbutt",
			"Crunch",
		}}, {
		ability: "Inner Focus",
		item:    "Lum Berry",
		species: "Dragonite",
		moves: [4]string{"Dragon Claw",
			"Aerial Ace",
			"Thunder Wave",
			"Dragon Dance",
		}}, {
		ability: "Inner Focus",
		item:    "Razor Claw",
		species: "Dragonite",
		moves: [4]string{"Dragon Rush",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Inner Focus",
		item:    "Expert Belt",
		species: "Dragonite",
		moves: [4]string{"Draco Meteor",
			"Flamethrower",
			"Thunderbolt",
			"Surf",
		}}, {
		ability: "Inner Focus",
		item:    "Choice Band",
		species: "Dragonite",
		moves: [4]string{"Outrage",
			"Giga Impact",
			"Earthquake",
			"Superpower",
		}}, {
		ability: "Overgrow",
		item:    "Heat Rock",
		species: "Meganium",
		moves: [4]string{"Solar Beam",
			"Ancient Power",
			"Synthesis",
			"Sunny Day",
		}}, {
		ability: "Overgrow",
		item:    "Big Root",
		species: "Meganium",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Toxic",
			"Substitute",
		}}, {
		ability: "Overgrow",
		item:    "Light Clay",
		species: "Meganium",
		moves: [4]string{"Leaf Storm",
			"Wring Out",
			"Light Screen",
			"Reflect",
		}}, {
		ability: "Overgrow",
		item:    "Lax Incense",
		species: "Meganium",
		moves: [4]string{"Frenzy Plant",
			"Ancient Power",
			"Hyper Beam",
			"Light Screen",
		}}, {
		ability: "Blaze",
		item:    "Scope Lens",
		species: "Typhlosion",
		moves: [4]string{"Fire Punch",
			"Thunder Punch",
			"Shadow Claw",
			"Quick Attack",
		}}, {
		ability: "Blaze",
		item:    "Salac Berry",
		species: "Typhlosion",
		moves: [4]string{"Blast Burn",
			"Earthquake",
			"Reversal",
			"Endure",
		}}, {
		ability: "Blaze",
		item:    "Shuca Berry",
		species: "Typhlosion",
		moves: [4]string{"Flare Blitz",
			"Earthquake",
			"Shadow Claw",
			"Aerial Ace",
		}}, {
		ability: "Blaze",
		item:    "White Herb",
		species: "Typhlosion",
		moves: [4]string{"Overheat",
			"Solar Beam",
			"Focus Blast",
			"Sunny Day",
		}}, {
		ability: "Torrent",
		item:    "King's Rock",
		species: "Feraligatr",
		moves: [4]string{"Waterfall",
			"Ice Fang",
			"Rock Slide",
			"Scary Face",
		}}, {
		ability: "Torrent",
		item:    "White Herb",
		species: "Feraligatr",
		moves: [4]string{"Aqua Tail",
			"Superpower",
			"Dragon Claw",
			"Shadow Claw",
		}}, {
		ability: "Torrent",
		item:    "Wise Glasses",
		species: "Feraligatr",
		moves: [4]string{"Hydro Cannon",
			"Ice Beam",
			"Focus Blast",
			"Ancient Power",
		}}, {
		ability: "Torrent",
		item:    "Lum Berry",
		species: "Feraligatr",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Ice Fang",
			"Dragon Dance",
		}}, {
		ability: "Inner Focus",
		item:    "Payapa Berry",
		species: "Crobat",
		moves: [4]string{"Cross Poison",
			"Aerial Ace",
			"Roost",
			"Hypnosis",
		}}, {
		ability: "Inner Focus",
		item:    "Razor Fang",
		species: "Crobat",
		moves: [4]string{"Air Slash",
			"Zen Headbutt",
			"Bite",
			"Twister",
		}}, {
		ability: "Inner Focus",
		item:    "King's Rock",
		species: "Crobat",
		moves: [4]string{"Air Slash",
			"Sludge Bomb",
			"Heat Wave",
			"Dark Pulse",
		}}, {
		ability: "Inner Focus",
		item:    "Razor Claw",
		species: "Crobat",
		moves: [4]string{"Cross Poison",
			"Brave Bird",
			"X-Scissor",
			"Zen Headbutt",
		}}, {
		ability: "Illuminate",
		item:    "Rindo Berry",
		species: "Lanturn",
		moves: [4]string{"Surf",
			"Discharge",
			"Thunder Wave",
			"Aqua Ring",
		}}, {
		ability: "Illuminate",
		item:    "Lum Berry",
		species: "Lanturn",
		moves: [4]string{"Dive",
			"Confuse Ray",
			"Thunder Wave",
			"Attract",
		}}, {
		ability: "Illuminate",
		item:    "Sitrus Berry",
		species: "Lanturn",
		moves: [4]string{"Hydro Pump",
			"Thunder",
			"Blizzard",
			"Rain Dance",
		}}, {
		ability: "Illuminate",
		item:    "Expert Belt",
		species: "Lanturn",
		moves: [4]string{"Surf",
			"Thunderbolt",
			"Ice Beam",
			"Signal Beam",
		}}, {
		ability: "Static",
		item:    "Shuca Berry",
		species: "Ampharos",
		moves: [4]string{"Thunderbolt",
			"Power Gem",
			"Light Screen",
			"Thunder Wave",
		}}, {
		ability: "Static",
		item:    "Cheri Berry",
		species: "Ampharos",
		moves: [4]string{"Thunder Punch",
			"Fire Punch",
			"Focus Punch",
			"Thunder Wave",
		}}, {
		ability: "Static",
		item:    "Chesto Berry",
		species: "Ampharos",
		moves: [4]string{"Charge Beam",
			"Hyper Beam",
			"Thunder Wave",
			"Rest",
		}}, {
		ability: "Static",
		item:    "Zoom Lens",
		species: "Ampharos",
		moves: [4]string{"Thunder",
			"Focus Blast",
			"Signal Beam",
			"Power Gem",
		}}, {
		ability: "Damp",
		item:    "Lax Incense",
		species: "Politoed",
		moves: [4]string{"Surf",
			"Hyper Voice",
			"Mud Bomb",
			"Swagger",
		}}, {
		ability: "Damp",
		item:    "Chesto Berry",
		species: "Politoed",
		moves: [4]string{"Dive",
			"Brick Break",
			"Hypnosis",
			"Perish Song",
		}}, {
		ability: "Damp",
		item:    "Chesto Berry",
		species: "Politoed",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Belly Drum",
			"Rest",
		}}, {
		ability: "Damp",
		item:    "Wacan Berry",
		species: "Politoed",
		moves: [4]string{"Hydro Pump",
			"Ice Beam",
			"Psychic",
			"Hypnosis",
		}}, {
		ability: "Water Absorb",
		item:    "Rindo Berry",
		species: "Quagsire",
		moves: [4]string{"Earthquake",
			"Aqua Tail",
			"Brick Break",
			"Counter",
		}}, {
		ability: "Water Absorb",
		item:    "Leftovers",
		species: "Quagsire",
		moves: [4]string{"Dive",
			"Yawn",
			"Curse",
			"Amnesia",
		}}, {
		ability: "Water Absorb",
		item:    "Quick Claw",
		species: "Quagsire",
		moves: [4]string{"Surf",
			"Earth Power",
			"Focus Blast",
			"Sludge Bomb",
		}}, {
		ability: "Water Absorb",
		item:    "Muscle Band",
		species: "Quagsire",
		moves: [4]string{"Earthquake",
			"Waterfall",
			"Stone Edge",
			"Ice Punch",
		}}, {
		ability: "Synchronize",
		item:    "Lum Berry",
		species: "Espeon",
		moves: [4]string{"Psychic",
			"Reflect",
			"Calm Mind",
			"Baton Pass",
		}}, {
		ability: "Synchronize",
		item:    "Bright Powder",
		species: "Espeon",
		moves: [4]string{"Psychic",
			"Swift",
			"Charm",
			"Attract",
		}}, {
		ability: "Synchronize",
		item:    "Lum Berry",
		species: "Espeon",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Hyper Beam",
			"Grass Knot",
		}}, {
		ability: "Synchronize",
		item:    "Wise Glasses",
		species: "Espeon",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Signal Beam",
			"Morning Sun",
		}}, {
		ability: "Synchronize",
		item:    "Leftovers",
		species: "Umbreon",
		moves: [4]string{"Payback",
			"Confuse Ray",
			"Curse",
			"Baton Pass",
		}}, {
		ability: "Synchronize",
		item:    "Leftovers",
		species: "Umbreon",
		moves: [4]string{"Toxic",
			"Mean Look",
			"Double Team",
			"Confuse Ray",
		}}, {
		ability: "Synchronize",
		item:    "Lax Incense",
		species: "Umbreon",
		moves: [4]string{"Feint Attack",
			"Swagger",
			"Psych Up",
			"Screech",
		}}, {
		ability: "Synchronize",
		item:    "Bright Powder",
		species: "Umbreon",
		moves: [4]string{"Payback",
			"Trump Card",
			"Curse",
			"Moonlight",
		}}, {
		ability: "Own Tempo",
		item:    "Shell Bell",
		species: "Slowking",
		moves: [4]string{"Psychic",
			"Brine",
			"Yawn",
			"Trick Room",
		}}, {
		ability: "Own Tempo",
		item:    "Quick Claw",
		species: "Slowking",
		moves: [4]string{"Zen Headbutt",
			"Aqua Tail",
			"Earthquake",
			"Curse",
		}}, {
		ability: "Own Tempo",
		item:    "Lum Berry",
		species: "Slowking",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Signal Beam",
			"Focus Blast",
		}}, {
		ability: "Own Tempo",
		item:    "Wise Glasses",
		species: "Slowking",
		moves: [4]string{"Psychic",
			"Surf",
			"Ice Beam",
			"Flamethrower",
		}}, {
		ability: "Sturdy",
		item:    "Occa Berry",
		species: "Forretress",
		moves: [4]string{"Gyro Ball",
			"Bug Bite",
			"Revenge",
			"Counter",
		}}, {
		ability: "Sturdy",
		item:    "Sitrus Berry",
		species: "Forretress",
		moves: [4]string{"Payback",
			"Stealth Rock",
			"Toxic Spikes",
			"Spikes",
		}}, {
		ability: "Sturdy",
		item:    "Leftovers",
		species: "Forretress",
		moves: [4]string{"Dig",
			"Swagger",
			"Toxic",
			"Double Team",
		}}, {
		ability: "Sturdy",
		item:    "Lax Incense",
		species: "Forretress",
		moves: [4]string{"Explosion",
			"Double-Edge",
			"Earthquake",
			"Rock Slide",
		}}, {
		ability: "Sturdy",
		item:    "Passho Berry",
		species: "Steelix",
		moves: [4]string{"Earthquake",
			"Iron Head",
			"Crunch",
			"Sandstorm",
		}}, {
		ability: "Sturdy",
		item:    "Shuca Berry",
		species: "Steelix",
		moves: [4]string{"Earthquake",
			"Fire Fang",
			"Thunder Fang",
			"Ice Fang",
		}}, {
		ability: "Sturdy",
		item:    "Iron Ball",
		species: "Steelix",
		moves: [4]string{"Gyro Ball",
			"Payback",
			"Swagger",
			"Curse",
		}}, {
		ability: "Sturdy",
		item:    "Quick Claw",
		species: "Steelix",
		moves: [4]string{"Gyro Ball",
			"Earthquake",
			"Stone Edge",
			"Explosion",
		}}, {
		ability: "Quick Feet",
		item:    "Razor Claw",
		species: "Granbull",
		moves: [4]string{"Return",
			"Rock Slide",
			"Crunch",
			"Thunder Wave",
		}}, {
		ability: "Quick Feet",
		item:    "Quick Claw",
		species: "Granbull",
		moves: [4]string{"Facade",
			"Fire Fang",
			"Thunder Fang",
			"Ice Fang",
		}}, {
		ability: "Quick Feet",
		item:    "Muscle Band",
		species: "Granbull",
		moves: [4]string{"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
			"Payback",
		}}, {
		ability: "Quick Feet",
		item:    "Life Orb",
		species: "Granbull",
		moves: [4]string{"Giga Impact",
			"Close Combat",
			"Earthquake",
			"Stone Edge",
		}}, {
		ability: "Technician",
		item:    "Bright Powder",
		species: "Scizor",
		moves: [4]string{"X-Scissor",
			"Bullet Punch",
			"Swords Dance",
			"Baton Pass",
		}}, {
		ability: "Technician",
		item:    "Sitrus Berry",
		species: "Scizor",
		moves: [4]string{"Metal Claw",
			"Night Slash",
			"Iron Defense",
			"Roost",
		}}, {
		ability: "Technician",
		item:    "Salac Berry",
		species: "Scizor",
		moves: [4]string{"X-Scissor",
			"Quick Attack",
			"Reversal",
			"Endure",
		}}, {
		ability: "Technician",
		item:    "Occa Berry",
		species: "Scizor",
		moves: [4]string{"X-Scissor",
			"Iron Head",
			"Aerial Ace",
			"Night Slash",
		}}, {
		ability: "Gluttony",
		item:    "Lax Incense",
		species: "Shuckle",
		moves: [4]string{"Stone Edge",
			"Bug Bite",
			"Swagger",
			"Power Trick",
		}}, {
		ability: "Gluttony",
		item:    "Grip Claw",
		species: "Shuckle",
		moves: [4]string{"Wrap",
			"Swagger",
			"Attract",
			"Toxic",
		}}, {
		ability: "Gluttony",
		item:    "Lax Incense",
		species: "Shuckle",
		moves: [4]string{"Gyro Ball",
			"Substitute",
			"Double Team",
			"Power Trick",
		}}, {
		ability: "Gluttony",
		item:    "Leftovers",
		species: "Shuckle",
		moves: [4]string{"Toxic",
			"Substitute",
			"Double Team",
			"Sandstorm",
		}}, {
		ability: "Guts",
		item:    "Focus Band",
		species: "Heracross",
		moves: [4]string{"Megahorn",
			"Focus Punch",
			"Swagger",
			"Attract",
		}}, {
		ability: "Guts",
		item:    "Scope Lens",
		species: "Heracross",
		moves: [4]string{"Close Combat",
			"Aerial Ace",
			"Night Slash",
			"Bulk Up",
		}}, {
		ability: "Guts",
		item:    "Coba Berry",
		species: "Heracross",
		moves: [4]string{"Megahorn",
			"Stone Edge",
			"Facade",
			"Shadow Claw",
		}}, {
		ability: "Guts",
		item:    "Salac Berry",
		species: "Heracross",
		moves: [4]string{"Megahorn",
			"Earthquake",
			"Reversal",
			"Endure",
		}}, {
		ability: "Quick Feet",
		item:    "Focus Sash",
		species: "Ursaring",
		moves: [4]string{"Slash",
			"Payback",
			"Avalanche",
			"Counter",
		}}, {
		ability: "Quick Feet",
		item:    "Life Orb",
		species: "Ursaring",
		moves: [4]string{"Hammer Arm",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Quick Feet",
		item:    "Toxic Orb",
		species: "Ursaring",
		moves: [4]string{"Facade",
			"Superpower",
			"Crunch",
			"Protect",
		}}, {
		ability: "Quick Feet",
		item:    "Quick Claw",
		species: "Ursaring",
		moves: [4]string{"Return",
			"Cross Chop",
			"Earthquake",
			"Aerial Ace",
		}}, {
		ability: "Sturdy",
		item:    "Occa Berry",
		species: "Skarmory",
		moves: [4]string{"Drill Peck",
			"Steel Wing",
			"Spikes",
			"Roar",
		}}, {
		ability: "Sturdy",
		item:    "Leftovers",
		species: "Skarmory",
		moves: [4]string{"Fly",
			"Toxic",
			"Double Team",
			"Roost",
		}}, {
		ability: "Sturdy",
		item:    "Razor Claw",
		species: "Skarmory",
		moves: [4]string{"Drill Peck",
			"Slash",
			"Payback",
			"Night Slash",
		}}, {
		ability: "Sturdy",
		item:    "Life Orb",
		species: "Skarmory",
		moves: [4]string{"Brave Bird",
			"Steel Wing",
			"X-Scissor",
			"Rock Slide",
		}}, {
		ability: "Flash Fire",
		item:    "Focus Sash",
		species: "Houndoom",
		moves: [4]string{"Fire Fang",
			"Crunch",
			"Roar",
			"Counter",
		}}, {
		ability: "Flash Fire",
		item:    "Focus Sash",
		species: "Houndoom",
		moves: [4]string{"Fire Fang",
			"Thunder Fang",
			"Reversal",
			"Endure",
		}}, {
		ability: "Flash Fire",
		item:    "Passho Berry",
		species: "Houndoom",
		moves: [4]string{"Flamethrower",
			"Shadow Ball",
			"Sludge Bomb",
			"Will-O-Wisp",
		}}, {
		ability: "Flash Fire",
		item:    "White Herb",
		species: "Houndoom",
		moves: [4]string{"Overheat",
			"Dark Pulse",
			"Solar Beam",
			"Sunny Day",
		}}, {
		ability: "Sniper",
		item:    "Razor Fang",
		species: "Kingdra",
		moves: [4]string{"Surf",
			"Dragon Pulse",
			"SmokeScreen",
			"Rain Dance",
		}}, {
		ability: "Sniper",
		item:    "Shell Bell",
		species: "Kingdra",
		moves: [4]string{"Brine",
			"Ice Beam",
			"Twister",
			"Yawn",
		}}, {
		ability: "Sniper",
		item:    "Lum Berry",
		species: "Kingdra",
		moves: [4]string{"Waterfall",
			"Outrage",
			"Iron Head",
			"Dragon Dance",
		}}, {
		ability: "Sniper",
		item:    "Wide Lens",
		species: "Kingdra",
		moves: [4]string{"Hydro Pump",
			"Draco Meteor",
			"Blizzard",
			"Signal Beam",
		}}, {
		ability: "Sturdy",
		item:    "Razor Claw",
		species: "Donphan",
		moves: [4]string{"Earthquake",
			"Rock Slide",
			"Poison Jab",
			"Sandstorm",
		}}, {
		ability: "Sturdy",
		item:    "White Herb",
		species: "Donphan",
		moves: [4]string{"Earthquake",
			"Superpower",
			"Gunk Shot",
			"Counter",
		}}, {
		ability: "Sturdy",
		item:    "Lax Incense",
		species: "Donphan",
		moves: [4]string{"Earthquake",
			"Gyro Ball",
			"Fire Fang",
			"Thunder Fang",
		}}, {
		ability: "Sturdy",
		item:    "Quick Claw",
		species: "Donphan",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Seed Bomb",
			"Fissure",
		}}, {
		ability: "Download",
		item:    "Cheri Berry",
		species: "Porygon2",
		moves: [4]string{"Tri Attack",
			"Charge Beam",
			"Thunder Wave",
			"Recycle",
		}}, {
		ability: "Download",
		item:    "Iron Ball",
		species: "Porygon2",
		moves: [4]string{"Tri Attack",
			"Thunderbolt",
			"Recover",
			"Trick Room",
		}}, {
		ability: "Download",
		item:    "Wise Glasses",
		species: "Porygon2",
		moves: [4]string{"Tri Attack",
			"Thunderbolt",
			"Psychic",
			"Ice Beam",
		}}, {
		ability: "Download",
		item:    "Lum Berry",
		species: "Porygon2",
		moves: [4]string{"Tri Attack",
			"Signal Beam",
			"Shadow Ball",
			"Ice Beam",
		}}, {
		ability: "Scrappy",
		item:    "Cheri Berry",
		species: "Miltank",
		moves: [4]string{"Return",
			"Iron Head",
			"Thunder Wave",
			"Milk Drink",
		}}, {
		ability: "Scrappy",
		item:    "Salac Berry",
		species: "Miltank",
		moves: [4]string{"Facade",
			"Zen Headbutt",
			"Reversal",
			"Endure",
		}}, {
		ability: "Scrappy",
		item:    "Scope Lens",
		species: "Miltank",
		moves: [4]string{"Dizzy Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Scrappy",
		item:    "Muscle Band",
		species: "Miltank",
		moves: [4]string{"Giga Impact",
			"Earthquake",
			"Rock Slide",
			"Zen Headbutt",
		}}, {
		ability: "Serene Grace",
		item:    "Chople Berry",
		species: "Blissey",
		moves: [4]string{"Hyper Beam",
			"Shadow Ball",
			"Water Pulse",
			"Sing",
		}}, {
		ability: "Serene Grace",
		item:    "Chesto Berry",
		species: "Blissey",
		moves: [4]string{"Toxic",
			"Double Team",
			"Soft-Boiled",
			"Counter",
		}}, {
		ability: "Serene Grace",
		item:    "Bright Powder",
		species: "Blissey",
		moves: [4]string{"Flamethrower",
			"Thunderbolt",
			"Ice Beam",
			"Calm Mind",
		}}, {
		ability: "Serene Grace",
		item:    "Leftovers",
		species: "Blissey",
		moves: [4]string{"Dream Eater",
			"Sing",
			"Soft-Boiled",
			"Counter",
		}}, {
		ability: "Sand Stream",
		item:    "Focus Band",
		species: "Tyranitar",
		moves: [4]string{"Rock Slide",
			"Payback",
			"Avalanche",
			"Curse",
		}}, {
		ability: "Sand Stream",
		item:    "Choice Scarf",
		species: "Tyranitar",
		moves: [4]string{"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
			"Aerial Ace",
		}}, {
		ability: "Sand Stream",
		item:    "White Herb",
		species: "Tyranitar",
		moves: [4]string{"Superpower",
			"Dragon Claw",
			"Shadow Claw",
			"Aqua Tail",
		}}, {
		ability: "Sand Stream",
		item:    "Chople Berry",
		species: "Tyranitar",
		moves: [4]string{"Stone Edge",
			"Crunch",
			"Earthquake",
			"Dragon Dance",
		}}, {
		ability: "Overgrow",
		item:    "Liechi Berry",
		species: "Sceptile",
		moves: [4]string{"Leaf Blade",
			"Crunch",
			"Quick Attack",
			"Screech",
		}}, {
		ability: "Overgrow",
		item:    "Leftovers",
		species: "Sceptile",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Toxic",
			"Double Team",
		}}, {
		ability: "Overgrow",
		item:    "Scope Lens",
		species: "Sceptile",
		moves: [4]string{"Leaf Blade",
			"X-Scissor",
			"Night Slash",
			"Aerial Ace",
		}}, {
		ability: "Overgrow",
		item:    "Occa Berry",
		species: "Sceptile",
		moves: [4]string{"Leaf Storm",
			"Dragon Pulse",
			"Focus Blast",
			"Hyper Beam",
		}}, {
		ability: "Blaze",
		item:    "Salac Berry",
		species: "Blaziken",
		moves: [4]string{"Blaze Kick",
			"Reversal",
			"Aerial Ace",
			"Endure",
		}}, {
		ability: "Blaze",
		item:    "Bright Powder",
		species: "Blaziken",
		moves: [4]string{"Blast Burn",
			"Focus Blast",
			"Solar Beam",
			"Sunny Day",
		}}, {
		ability: "Blaze",
		item:    "Passho Berry",
		species: "Blaziken",
		moves: [4]string{"Blaze Kick",
			"Earthquake",
			"Shadow Claw",
			"Stone Edge",
		}}, {
		ability: "Blaze",
		item:    "White Herb",
		species: "Blaziken",
		moves: [4]string{"Flare Blitz",
			"Superpower",
			"Thunder Punch",
			"Night Slash",
		}}, {
		ability: "Torrent",
		item:    "Shell Bell",
		species: "Swampert",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Ice Punch",
			"Protect",
		}}, {
		ability: "Torrent",
		item:    "Lum Berry",
		species: "Swampert",
		moves: [4]string{"Aqua Tail",
			"Earthquake",
			"Hammer Arm",
			"Curse",
		}}, {
		ability: "Torrent",
		item:    "Expert Belt",
		species: "Swampert",
		moves: [4]string{"Muddy Water",
			"Earth Power",
			"Ice Beam",
			"Counter",
		}}, {
		ability: "Torrent",
		item:    "Rindo Berry",
		species: "Swampert",
		moves: [4]string{"Earthquake",
			"Aqua Tail",
			"Avalanche",
			"Mirror Coat",
		}}, {
		ability: "Rain Dish",
		item:    "Muscle Band",
		species: "Ludicolo",
		moves: [4]string{"Waterfall",
			"Razor Leaf",
			"Drain Punch",
			"Swords Dance",
		}}, {
		ability: "Rain Dish",
		item:    "Leftovers",
		species: "Ludicolo",
		moves: [4]string{"Leech Seed",
			"Toxic",
			"Double Team",
			"Rain Dance",
		}}, {
		ability: "Rain Dish",
		item:    "Wide Lens",
		species: "Ludicolo",
		moves: [4]string{"Hydro Pump",
			"Grass Knot",
			"Blizzard",
			"Focus Blast",
		}}, {
		ability: "Rain Dish",
		item:    "Lum Berry",
		species: "Ludicolo",
		moves: [4]string{"Surf",
			"Giga Drain",
			"Ice Beam",
			"Rain Dance",
		}}, {
		ability: "Early Bird",
		item:    "Persim Berry",
		species: "Shiftry",
		moves: [4]string{"Seed Bomb",
			"Feint Attack",
			"X-Scissor",
			"Fake Out",
		}}, {
		ability: "Early Bird",
		item:    "Leftovers",
		species: "Shiftry",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Double Team",
			"Synthesis",
		}}, {
		ability: "Early Bird",
		item:    "White Herb",
		species: "Shiftry",
		moves: [4]string{"Leaf Storm",
			"Dark Pulse",
			"Focus Blast",
			"Shadow Ball",
		}}, {
		ability: "Early Bird",
		item:    "Cheri Berry",
		species: "Shiftry",
		moves: [4]string{"Seed Bomb",
			"Sucker Punch",
			"Aerial Ace",
			"Explosion",
		}}, {
		ability: "Trace",
		item:    "Lum Berry",
		species: "Gardevoir",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Thunder Wave",
			"Confuse Ray",
		}}, {
		ability: "Trace",
		item:    "Chesto Berry",
		species: "Gardevoir",
		moves: [4]string{"Psychic",
			"Thunderbolt",
			"Calm Mind",
			"Rest",
		}}, {
		ability: "Trace",
		item:    "Bright Powder",
		species: "Gardevoir",
		moves: [4]string{"Psychic",
			"Charge Beam",
			"Energy Ball",
			"Focus Blast",
		}}, {
		ability: "Trace",
		item:    "Wise Glasses",
		species: "Gardevoir",
		moves: [4]string{"Psychic",
			"Thunderbolt",
			"Shadow Ball",
			"Destiny Bond",
		}}, {
		ability: "Poison Heal",
		item:    "Focus Sash",
		species: "Breloom",
		moves: [4]string{"Seed Bomb",
			"Sky Uppercut",
			"Rock Slide",
			"Counter",
		}}, {
		ability: "Poison Heal",
		item:    "Big Root",
		species: "Breloom",
		moves: [4]string{"Drain Punch",
			"Giga Drain",
			"Synthesis",
			"Leech Seed",
		}}, {
		ability: "Poison Heal",
		item:    "Toxic Orb",
		species: "Breloom",
		moves: [4]string{"Dynamic Punch",
			"Thunder Punch",
			"Stone Edge",
			"Facade",
		}}, {
		ability: "Poison Heal",
		item:    "Shell Bell",
		species: "Breloom",
		moves: [4]string{"Focus Punch",
			"Seed Bomb",
			"Giga Impact",
			"Spore",
		}}, {
		ability: "Truant",
		item:    "Lax Incense",
		species: "Slaking",
		moves: [4]string{"Facade",
			"Shadow Claw",
			"Slack Off",
			"Yawn",
		}}, {
		ability: "Truant",
		item:    "Lum Berry",
		species: "Slaking",
		moves: [4]string{"Crush Claw",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Truant",
		item:    "Life Orb",
		species: "Slaking",
		moves: [4]string{"Return",
			"Night Slash",
			"Gunk Shot",
			"Aerial Ace",
		}}, {
		ability: "Truant",
		item:    "Muscle Band",
		species: "Slaking",
		moves: [4]string{"Giga Impact",
			"Earthquake",
			"Hammer Arm",
			"Shadow Claw",
		}}, {
		ability: "Soundproof",
		item:    "Chople Berry",
		species: "Exploud",
		moves: [4]string{"Hyper Voice",
			"Extrasensory",
			"Water Pulse",
			"Torment",
		}}, {
		ability: "Soundproof",
		item:    "Life Orb",
		species: "Exploud",
		moves: [4]string{"Facade",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Soundproof",
		item:    "Life Orb",
		species: "Exploud",
		moves: [4]string{"Facade",
			"Earthquake",
			"Avalanche",
			"Crunch",
		}}, {
		ability: "Soundproof",
		item:    "White Herb",
		species: "Exploud",
		moves: [4]string{"Hyper Voice",
			"Overheat",
			"Surf",
			"Ice Beam",
		}}, {
		ability: "Guts",
		item:    "Persim Berry",
		species: "Hariyama",
		moves: [4]string{"Arm Thrust",
			"Earthquake",
			"Facade",
			"Fake Out",
		}}, {
		ability: "Guts",
		item:    "Iron Ball",
		species: "Hariyama",
		moves: [4]string{"Revenge",
			"Payback",
			"Fling",
			"Fake Out",
		}}, {
		ability: "Guts",
		item:    "Life Orb",
		species: "Hariyama",
		moves: [4]string{"Dynamic Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Guts",
		item:    "Scope Lens",
		species: "Hariyama",
		moves: [4]string{"Cross Chop",
			"Earthquake",
			"Stone Edge",
			"Poison Jab",
		}}, {
		ability: "Rock Head",
		item:    "Quick Claw",
		species: "Aggron",
		moves: [4]string{"Iron Head",
			"Rock Slide",
			"Sandstorm",
			"Screech",
		}}, {
		ability: "Rock Head",
		item:    "Quick Claw",
		species: "Aggron",
		moves: [4]string{"Metal Claw",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Rock Head",
		item:    "Muscle Band",
		species: "Aggron",
		moves: [4]string{"Iron Tail",
			"Dragon Rush",
			"Avalanche",
			"Aerial Ace",
		}}, {
		ability: "Rock Head",
		item:    "Focus Sash",
		species: "Aggron",
		moves: [4]string{"Metal Burst",
			"Stone Edge",
			"Earthquake",
			"Shadow Claw",
		}}, {
		ability: "Pure Power",
		item:    "Salac Berry",
		species: "Medicham",
		moves: [4]string{"Zen Headbutt",
			"Reversal",
			"Endure",
			"Fake Out",
		}}, {
		ability: "Pure Power",
		item:    "Cheri Berry",
		species: "Medicham",
		moves: [4]string{"Drain Punch",
			"Poison Jab",
			"Detect",
			"Recover",
		}}, {
		ability: "Pure Power",
		item:    "Wise Glasses",
		species: "Medicham",
		moves: [4]string{"Psychic",
			"Focus Blast",
			"Shadow Ball",
			"Calm Mind",
		}}, {
		ability: "Pure Power",
		item:    "Scope Lens",
		species: "Medicham",
		moves: [4]string{"Psycho Cut",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Lightning Rod",
		item:    "Shuca Berry",
		species: "Manectric",
		moves: [4]string{"Thunder Fang",
			"Crunch",
			"Roar",
			"Thunder Wave",
		}}, {
		ability: "Lightning Rod",
		item:    "Damp Rock",
		species: "Manectric",
		moves: [4]string{"Thunder",
			"Hyper Beam",
			"Thunder Wave",
			"Rain Dance",
		}}, {
		ability: "Lightning Rod",
		item:    "Quick Claw",
		species: "Manectric",
		moves: [4]string{"Thunder Fang",
			"Fire Fang",
			"Ice Fang",
			"Bite",
		}}, {
		ability: "Lightning Rod",
		item:    "Bright Powder",
		species: "Manectric",
		moves: [4]string{"Thunderbolt",
			"Flamethrower",
			"Signal Beam",
			"Swift",
		}}, {
		ability: "Oblivious",
		item:    "Sitrus Berry",
		species: "Wailord",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Attract",
			"Double Team",
		}}, {
		ability: "Oblivious",
		item:    "Chesto Berry",
		species: "Wailord",
		moves: [4]string{"Whirlpool",
			"Toxic",
			"Amnesia",
			"Rest",
		}}, {
		ability: "Oblivious",
		item:    "Leftovers",
		species: "Wailord",
		moves: [4]string{"Waterfall",
			"Avalanche",
			"Earthquake",
			"Curse",
		}}, {
		ability: "Oblivious",
		item:    "Quick Claw",
		species: "Wailord",
		moves: [4]string{"Hydro Pump",
			"Blizzard",
			"Hyper Beam",
			"Fissure",
		}}, {
		ability: "Levitate",
		item:    "Yache Berry",
		species: "Flygon",
		moves: [4]string{"Earthquake",
			"Dragon Claw",
			"Roost",
			"Sandstorm",
		}}, {
		ability: "Levitate",
		item:    "Razor Fang",
		species: "Flygon",
		moves: [4]string{"Fissure",
			"Fire Punch",
			"Thunder Punch",
			"Aerial Ace",
		}}, {
		ability: "Levitate",
		item:    "White Herb",
		species: "Flygon",
		moves: [4]string{"Draco Meteor",
			"Earth Power",
			"Flamethrower",
			"Giga Drain",
		}}, {
		ability: "Levitate",
		item:    "Lum Berry",
		species: "Flygon",
		moves: [4]string{"Earthquake",
			"Outrage",
			"Crunch",
			"Stone Edge",
		}}, {
		ability: "Natural Cure",
		item:    "Chesto Berry",
		species: "Altaria",
		moves: [4]string{"Dragon Claw",
			"Aerial Ace",
			"Dragon Dance",
			"Rest",
		}}, {
		ability: "Natural Cure",
		item:    "Shell Bell",
		species: "Altaria",
		moves: [4]string{"Dragon Pulse",
			"Ominous Wind",
			"Sing",
			"Perish Song",
		}}, {
		ability: "Natural Cure",
		item:    "Bright Powder",
		species: "Altaria",
		moves: [4]string{"Dragon Rush",
			"Sky Attack",
			"Earthquake",
			"Dragon Dance",
		}}, {
		ability: "Natural Cure",
		item:    "White Herb",
		species: "Altaria",
		moves: [4]string{"Draco Meteor",
			"Air Cutter",
			"Flamethrower",
			"Ice Beam",
		}}, {
		ability: "Anticipation",
		item:    "Shell Bell",
		species: "Whiscash",
		moves: [4]string{"Surf",
			"Earth Power",
			"Icy Wind",
			"Amnesia",
		}}, {
		ability: "Anticipation",
		item:    "Persim Berry",
		species: "Whiscash",
		moves: [4]string{"Aqua Tail",
			"Earthquake",
			"Rock Slide",
			"Thrash",
		}}, {
		ability: "Anticipation",
		item:    "Zoom Lens",
		species: "Whiscash",
		moves: [4]string{"Hydro Pump",
			"Earth Power",
			"Blizzard",
			"Fissure",
		}}, {
		ability: "Anticipation",
		item:    "Muscle Band",
		species: "Whiscash",
		moves: [4]string{"Earthquake",
			"Aqua Tail",
			"Zen Headbutt",
			"Stone Edge",
		}}, {
		ability: "Levitate",
		item:    "Kasib Berry",
		species: "Claydol",
		moves: [4]string{"Earthquake",
			"Zen Headbutt",
			"Grass Knot",
			"Trick Room",
		}}, {
		ability: "Levitate",
		item:    "Rindo Berry",
		species: "Claydol",
		moves: [4]string{"Earth Power",
			"Ancient Power",
			"Signal Beam",
			"Shadow Ball",
		}}, {
		ability: "Levitate",
		item:    "Wise Glasses",
		species: "Claydol",
		moves: [4]string{"Earth Power",
			"Psychic",
			"Charge Beam",
			"Ice Beam",
		}}, {
		ability: "Levitate",
		item:    "Lax Incense",
		species: "Claydol",
		moves: [4]string{"Earthquake",
			"Zen Headbutt",
			"Rock Slide",
			"Explosion",
		}}, {
		ability: "Suction Cups",
		item:    "Razor Claw",
		species: "Cradily",
		moves: [4]string{"Ancient Power",
			"Energy Ball",
			"Confuse Ray",
			"Sandstorm",
		}}, {
		ability: "Suction Cups",
		item:    "Leftovers",
		species: "Cradily",
		moves: [4]string{"Toxic",
			"Stockpile",
			"Double Team",
			"Ingrain",
		}}, {
		ability: "Suction Cups",
		item:    "Big Root",
		species: "Cradily",
		moves: [4]string{"Giga Drain",
			"Sludge Bomb",
			"Recover",
			"Ingrain",
		}}, {
		ability: "Suction Cups",
		item:    "Leftovers",
		species: "Cradily",
		moves: [4]string{"Stone Edge",
			"Seed Bomb",
			"Earthquake",
			"Mirror Coat",
		}}, {
		ability: "Battle Armor",
		item:    "Razor Claw",
		species: "Armaldo",
		moves: [4]string{"X-Scissor",
			"Rock Slide",
			"Earthquake",
			"Iron Defense",
		}}, {
		ability: "Battle Armor",
		item:    "Scope Lens",
		species: "Armaldo",
		moves: [4]string{"Crush Claw",
			"Aqua Tail",
			"Aerial Ace",
			"Swagger",
		}}, {
		ability: "Battle Armor",
		item:    "Choice Band",
		species: "Armaldo",
		moves: [4]string{"Stone Edge",
			"Superpower",
			"Earthquake",
			"Giga Impact",
		}}, {
		ability: "Battle Armor",
		item:    "Life Orb",
		species: "Armaldo",
		moves: [4]string{"Stone Edge",
			"X-Scissor",
			"Earthquake",
			"Cross Poison",
		}}, {
		ability: "Marvel Scale",
		item:    "Shell Bell",
		species: "Milotic",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Attract",
			"Hypnosis",
		}}, {
		ability: "Marvel Scale",
		item:    "Leftovers",
		species: "Milotic",
		moves: [4]string{"Toxic",
			"Confuse Ray",
			"Double Team",
			"Aqua Ring",
		}}, {
		ability: "Marvel Scale",
		item:    "Wide Lens",
		species: "Milotic",
		moves: [4]string{"Hydro Pump",
			"Blizzard",
			"Mirror Coat",
			"Recover",
		}}, {
		ability: "Marvel Scale",
		item:    "Lum Berry",
		species: "Milotic",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Dragon Pulse",
			"Recover",
		}}, {
		ability: "Super Luck",
		item:    "Chople Berry",
		species: "Absol",
		moves: [4]string{"Sucker Punch",
			"Facade",
			"Double Team",
			"Taunt",
		}}, {
		ability: "Super Luck",
		item:    "Quick Claw",
		species: "Absol",
		moves: [4]string{"Punishment",
			"Swagger",
			"Attract",
			"Thunder Wave",
		}}, {
		ability: "Super Luck",
		item:    "Razor Claw",
		species: "Absol",
		moves: [4]string{"Night Slash",
			"Psycho Cut",
			"X-Scissor",
			"Aerial Ace",
		}}, {
		ability: "Super Luck",
		item:    "Choice Band",
		species: "Absol",
		moves: [4]string{"Night Slash",
			"Superpower",
			"Giga Impact",
			"Zen Headbutt",
		}}, {
		ability: "Ice Body",
		item:    "Iron Ball",
		species: "Glalie",
		moves: [4]string{"Avalanche",
			"Payback",
			"Gyro Ball",
			"Ice Shard",
		}}, {
		ability: "Ice Body",
		item:    "Lum Berry",
		species: "Glalie",
		moves: [4]string{"Ice Fang",
			"Crunch",
			"Earthquake",
			"Explosion",
		}}, {
		ability: "Ice Body",
		item:    "Scope Lens",
		species: "Glalie",
		moves: [4]string{"Ice Beam",
			"Shadow Ball",
			"Signal Beam",
			"Water Pulse",
		}}, {
		ability: "Ice Body",
		item:    "Lax Incense",
		species: "Glalie",
		moves: [4]string{"Blizzard",
			"Dark Pulse",
			"Sheer Cold",
			"Hail",
		}}, {
		ability: "Ice Body",
		item:    "Chople Berry",
		species: "Walrein",
		moves: [4]string{"Ice Fang",
			"Aqua Tail",
			"Swagger",
			"Encore",
		}}, {
		ability: "Ice Body",
		item:    "Life Orb",
		species: "Walrein",
		moves: [4]string{"Avalanche",
			"Earthquake",
			"Crunch",
			"Curse",
		}}, {
		ability: "Ice Body",
		item:    "Lax Incense",
		species: "Walrein",
		moves: [4]string{"Sheer Cold",
			"Fissure",
			"Rest",
			"Sleep Talk",
		}}, {
		ability: "Ice Body",
		item:    "Leftovers",
		species: "Walrein",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Signal Beam",
			"Hail",
		}}, {
		ability: "Intimidate",
		item:    "Cheri Berry",
		species: "Salamence",
		moves: [4]string{"Dragon Claw",
			"Aerial Ace",
			"Aqua Tail",
			"Scary Face",
		}}, {
		ability: "Intimidate",
		item:    "Razor Fang",
		species: "Salamence",
		moves: [4]string{"Dragon Claw",
			"Fire Fang",
			"Thunder Fang",
			"Dragon Dance",
		}}, {
		ability: "Intimidate",
		item:    "Wise Glasses",
		species: "Salamence",
		moves: [4]string{"Draco Meteor",
			"Hydro Pump",
			"Flamethrower",
			"Ominous Wind",
		}}, {
		ability: "Intimidate",
		item:    "Lum Berry",
		species: "Salamence",
		moves: [4]string{"Outrage",
			"Crunch",
			"Earthquake",
			"Zen Headbutt",
		}}, {
		ability: "Clear Body",
		item:    "Bright Powder",
		species: "Metagross",
		moves: [4]string{"Zen Headbutt",
			"Bullet Punch",
			"Facade",
			"Light Screen",
		}}, {
		ability: "Clear Body",
		item:    "Wise Glasses",
		species: "Metagross",
		moves: [4]string{"Psychic",
			"Flash Cannon",
			"Shadow Ball",
			"Sludge Bomb",
		}}, {
		ability: "Clear Body",
		item:    "Occa Berry",
		species: "Metagross",
		moves: [4]string{"Hammer Arm",
			"Thunder Punch",
			"Ice Punch",
			"Aerial Ace",
		}}, {
		ability: "Clear Body",
		item:    "Quick Claw",
		species: "Metagross",
		moves: [4]string{"Meteor Mash",
			"Zen Headbutt",
			"Earthquake",
			"Explosion",
		}}, {
		ability: "Overgrow",
		item:    "Yache Berry",
		species: "Torterra",
		moves: [4]string{"Earthquake",
			"Grass Knot",
			"Rock Slide",
			"Curse",
		}}, {
		ability: "Overgrow",
		item:    "Leftovers",
		species: "Torterra",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Synthesis",
			"Amnesia",
		}}, {
		ability: "Overgrow",
		item:    "Lax Incense",
		species: "Torterra",
		moves: [4]string{"Frenzy Plant",
			"Earth Power",
			"Hyper Beam",
			"Leech Seed",
		}}, {
		ability: "Overgrow",
		item:    "Quick Claw",
		species: "Torterra",
		moves: [4]string{"Wood Hammer",
			"Earthquake",
			"Stone Edge",
			"Crunch",
		}}, {
		ability: "Blaze",
		item:    "Coba Berry",
		species: "Infernape",
		moves: [4]string{"Close Combat",
			"Fire Punch",
			"U-turn",
			"Fake Out",
		}}, {
		ability: "Blaze",
		item:    "Muscle Band",
		species: "Infernape",
		moves: [4]string{"Blaze Kick",
			"Shadow Claw",
			"Thunder Punch",
			"Gunk Shot",
		}}, {
		ability: "Blaze",
		item:    "Bright Powder",
		species: "Infernape",
		moves: [4]string{"Flamethrower",
			"Focus Blast",
			"Solar Beam",
			"Sunny Day",
		}}, {
		ability: "Blaze",
		item:    "King's Rock",
		species: "Infernape",
		moves: [4]string{"Flare Blitz",
			"Close Combat",
			"Earthquake",
			"Thunder Punch",
		}}, {
		ability: "Torrent",
		item:    "Razor Claw",
		species: "Empoleon",
		moves: [4]string{"Waterfall",
			"Metal Claw",
			"Brick Break",
			"Knock Off",
		}}, {
		ability: "Torrent",
		item:    "Razor Claw",
		species: "Empoleon",
		moves: [4]string{"Drill Peck",
			"Aqua Jet",
			"Shadow Claw",
			"Rock Slide",
		}}, {
		ability: "Torrent",
		item:    "Quick Claw",
		species: "Empoleon",
		moves: [4]string{"Surf",
			"Earthquake",
			"Blizzard",
			"Signal Beam",
		}}, {
		ability: "Torrent",
		item:    "Quick Claw",
		species: "Empoleon",
		moves: [4]string{"Hydro Cannon",
			"Flash Cannon",
			"Drill Peck",
			"Earthquake",
		}}, {
		ability: "Intimidate",
		item:    "King's Rock",
		species: "Staraptor",
		moves: [4]string{"Return",
			"Aerial Ace",
			"Double Team",
			"Roost",
		}}, {
		ability: "Intimidate",
		item:    "King's Rock",
		species: "Staraptor",
		moves: [4]string{"Endeavor",
			"Aerial Ace",
			"Endure",
			"Quick Attack",
		}}, {
		ability: "Intimidate",
		item:    "Muscle Band",
		species: "Staraptor",
		moves: [4]string{"Brave Bird",
			"Return",
			"Steel Wing",
			"Pursuit",
		}}, {
		ability: "Intimidate",
		item:    "Choice Band",
		species: "Staraptor",
		moves: [4]string{"Brave Bird",
			"Giga Impact",
			"Close Combat",
			"U-turn",
		}}, {
		ability: "Intimidate",
		item:    "Razor Claw",
		species: "Luxray",
		moves: [4]string{"Thunder Fang",
			"Crunch",
			"Howl",
			"Charge",
		}}, {
		ability: "Intimidate",
		item:    "Wise Glasses",
		species: "Luxray",
		moves: [4]string{"Thunderbolt",
			"Signal Beam",
			"Thunder Wave",
			"Magnet Rise",
		}}, {
		ability: "Intimidate",
		item:    "White Herb",
		species: "Luxray",
		moves: [4]string{"Thunder Fang",
			"Ice Fang",
			"Superpower",
			"Thunder Wave",
		}}, {
		ability: "Intimidate",
		item:    "Muscle Band",
		species: "Luxray",
		moves: [4]string{"Thunder Fang",
			"Ice Fang",
			"Crunch",
			"Thunder Wave",
		}}, {
		ability: "Poison Point",
		item:    "Coba Berry",
		species: "Roserade",
		moves: [4]string{"Sludge Bomb",
			"Magical Leaf",
			"Stun Spore",
			"Mud-Slap",
		}}, {
		ability: "Poison Point",
		item:    "Big Root",
		species: "Roserade",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Ingrain",
			"Synthesis",
		}}, {
		ability: "Poison Point",
		item:    "White Herb",
		species: "Roserade",
		moves: [4]string{"Leaf Storm",
			"Sludge Bomb",
			"Hyper Beam",
			"Grass Whistle",
		}}, {
		ability: "Poison Point",
		item:    "White Herb",
		species: "Roserade",
		moves: [4]string{"Leaf Storm",
			"Sludge Bomb",
			"Shadow Ball",
			"Weather Ball",
		}}, {
		ability: "Mold Breaker",
		item:    "Toxic Orb",
		species: "Rampardos",
		moves: [4]string{"Rock Slide",
			"Facade",
			"Crunch",
			"Screech",
		}}, {
		ability: "Mold Breaker",
		item:    "Iron Ball",
		species: "Rampardos",
		moves: [4]string{"Stone Edge",
			"Payback",
			"Avalanche",
			"Fling",
		}}, {
		ability: "Mold Breaker",
		item:    "Life Orb",
		species: "Rampardos",
		moves: [4]string{"Head Smash",
			"Zen Headbutt",
			"Fire Punch",
			"Thunder Punch",
		}}, {
		ability: "Mold Breaker",
		item:    "Choice Scarf",
		species: "Rampardos",
		moves: [4]string{"Head Smash",
			"Earthquake",
			"Giga Impact",
			"Superpower",
		}}, {
		ability: "Sturdy",
		item:    "Focus Band",
		species: "Bastiodon",
		moves: [4]string{"Iron Head",
			"Stone Edge",
			"Swagger",
			"Taunt",
		}}, {
		ability: "Sturdy",
		item:    "Persim Berry",
		species: "Bastiodon",
		moves: [4]string{"Ancient Power",
			"Flamethrower",
			"Thunderbolt",
			"Ice Beam",
		}}, {
		ability: "Sturdy",
		item:    "Leftovers",
		species: "Bastiodon",
		moves: [4]string{"Iron Head",
			"Fissure",
			"Double Team",
			"Iron Defense",
		}}, {
		ability: "Sturdy",
		item:    "Focus Sash",
		species: "Bastiodon",
		moves: [4]string{"Metal Burst",
			"Stone Edge",
			"Avalanche",
			"Curse",
		}}, {
		ability: "Pressure",
		item:    "Scope Lens",
		species: "Vespiquen",
		moves: [4]string{"Silver Wind",
			"Air Cutter",
			"Ominous Wind",
			"Swagger",
		}}, {
		ability: "Pressure",
		item:    "Persim Berry",
		species: "Vespiquen",
		moves: [4]string{"X-Scissor",
			"Toxic",
			"Heal Order",
			"Destiny Bond",
		}}, {
		ability: "Pressure",
		item:    "Muscle Band",
		species: "Vespiquen",
		moves: [4]string{"X-Scissor",
			"Aerial Ace",
			"Pursuit",
			"U-turn",
		}}, {
		ability: "Pressure",
		item:    "Shell Bell",
		species: "Vespiquen",
		moves: [4]string{"Attack Order",
			"Defend Order",
			"Heal Order",
			"Confuse Ray",
		}}, {
		ability: "Swift Swim",
		item:    "Sitrus Berry",
		species: "Floatzel",
		moves: [4]string{"Waterfall",
			"Ice Punch",
			"Quick Attack",
			"Rain Dance",
		}}, {
		ability: "Swift Swim",
		item:    "Chesto Berry",
		species: "Floatzel",
		moves: [4]string{"Waterfall",
			"Focus Punch",
			"Double Team",
			"Attract",
		}}, {
		ability: "Swift Swim",
		item:    "Wave Incense",
		species: "Floatzel",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Focus Blast",
			"Rain Dance",
		}}, {
		ability: "Swift Swim",
		item:    "Razor Fang",
		species: "Floatzel",
		moves: [4]string{"Aqua Tail",
			"Ice Fang",
			"Crunch",
			"Brick Break",
		}}, {
		ability: "Storm Drain",
		item:    "Focus Sash",
		species: "Gastrodon",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Recover",
			"Mirror Coat",
		}}, {
		ability: "Storm Drain",
		item:    "Zoom Lens",
		species: "Gastrodon",
		moves: [4]string{"Muddy Water",
			"Mud Bomb",
			"Recover",
			"Yawn",
		}}, {
		ability: "Storm Drain",
		item:    "Shell Bell",
		species: "Gastrodon",
		moves: [4]string{"Waterfall",
			"Earthquake",
			"Stone Edge",
			"Fissure",
		}}, {
		ability: "Storm Drain",
		item:    "Wise Glasses",
		species: "Gastrodon",
		moves: [4]string{"Surf",
			"Earth Power",
			"Ice Beam",
			"Sludge Bomb",
		}}, {
		ability: "Pickup",
		item:    "Muscle Band",
		species: "Ambipom",
		moves: [4]string{"Double Hit",
			"Shadow Claw",
			"Brick Break",
			"Knock Off",
		}}, {
		ability: "Pickup",
		item:    "Metronome",
		species: "Ambipom",
		moves: [4]string{"Last Resort",
			"Thunder Wave",
			"Protect",
			"Fake Out",
		}}, {
		ability: "Pickup",
		item:    "Life Orb",
		species: "Ambipom",
		moves: [4]string{"Double Hit",
			"Gunk Shot",
			"Seed Bomb",
			"Aerial Ace",
		}}, {
		ability: "Pickup",
		item:    "Life Orb",
		species: "Ambipom",
		moves: [4]string{"Double Hit",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Unburden",
		item:    "Salac Berry",
		species: "Drifblim",
		moves: [4]string{"Ominous Wind",
			"Air Cutter",
			"Baton Pass",
			"Endure",
		}}, {
		ability: "Unburden",
		item:    "Black Sludge",
		species: "Drifblim",
		moves: [4]string{"Payback",
			"Facade",
			"Will-O-Wisp",
			"Trick",
		}}, {
		ability: "Unburden",
		item:    "Wise Glasses",
		species: "Drifblim",
		moves: [4]string{"Psychic",
			"Thunderbolt",
			"Icy Wind",
			"Destiny Bond",
		}}, {
		ability: "Unburden",
		item:    "Lax Incense",
		species: "Drifblim",
		moves: [4]string{"Shadow Ball",
			"Air Cutter",
			"Silver Wind",
			"Explosion",
		}}, {
		ability: "Klutz",
		item:    "Focus Band",
		species: "Lopunny",
		moves: [4]string{"Return",
			"Drain Punch",
			"Charm",
			"Mirror Coat",
		}}, {
		ability: "Klutz",
		item:    "Bright Powder",
		species: "Lopunny",
		moves: [4]string{"Focus Punch",
			"Sweet Kiss",
			"Attract",
			"Thunder Wave",
		}}, {
		ability: "Klutz",
		item:    "Wise Glasses",
		species: "Lopunny",
		moves: [4]string{"Charge Beam",
			"Ice Beam",
			"Shadow Ball",
			"Focus Blast",
		}}, {
		ability: "Klutz",
		item:    "Muscle Band",
		species: "Lopunny",
		moves: [4]string{"Dizzy Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Levitate",
		item:    "Kasib Berry",
		species: "Mismagius",
		moves: [4]string{"Shadow Ball",
			"Power Gem",
			"Magical Leaf",
			"Memento",
		}}, {
		ability: "Levitate",
		item:    "Lum Berry",
		species: "Mismagius",
		moves: [4]string{"Shadow Ball",
			"Confuse Ray",
			"Perish Song",
			"Mean Look",
		}}, {
		ability: "Levitate",
		item:    "Wise Glasses",
		species: "Mismagius",
		moves: [4]string{"Shadow Ball",
			"Energy Ball",
			"Icy Wind",
			"Destiny Bond",
		}}, {
		ability: "Levitate",
		item:    "Focus Sash",
		species: "Mismagius",
		moves: [4]string{"Shadow Ball",
			"Psychic",
			"Thunderbolt",
			"Destiny Bond",
		}}, {
		ability: "Super Luck",
		item:    "Wacan Berry",
		species: "Honchkrow",
		moves: [4]string{"Night Slash",
			"Aerial Ace",
			"Torment",
			"Taunt",
		}}, {
		ability: "Super Luck",
		item:    "White Herb",
		species: "Honchkrow",
		moves: [4]string{"Superpower",
			"Pluck",
			"Confuse Ray",
			"Thunder Wave",
		}}, {
		ability: "Super Luck",
		item:    "Life Orb",
		species: "Honchkrow",
		moves: [4]string{"Dark Pulse",
			"Air Cutter",
			"Psychic",
			"Shadow Ball",
		}}, {
		ability: "Super Luck",
		item:    "Scope Lens",
		species: "Honchkrow",
		moves: [4]string{"Night Slash",
			"Drill Peck",
			"Sucker Punch",
			"Steel Wing",
		}}, {
		ability: "Aftermath",
		item:    "Razor Claw",
		species: "Skuntank",
		moves: [4]string{"Sucker Punch",
			"Poison Jab",
			"Slash",
			"Screech",
		}}, {
		ability: "Aftermath",
		item:    "Chesto Berry",
		species: "Skuntank",
		moves: [4]string{"Crunch",
			"Toxic",
			"Swagger",
			"Double Team",
		}}, {
		ability: "Aftermath",
		item:    "Shuca Berry",
		species: "Skuntank",
		moves: [4]string{"Sludge Bomb",
			"Dark Pulse",
			"Flamethrower",
			"Shadow Ball",
		}}, {
		ability: "Aftermath",
		item:    "Muscle Band",
		species: "Skuntank",
		moves: [4]string{"Poison Jab",
			"Night Slash",
			"Crunch",
			"Explosion",
		}}, {
		ability: "Heatproof",
		item:    "King's Rock",
		species: "Bronzong",
		moves: [4]string{"Extrasensory",
			"Iron Head",
			"Rock Slide",
			"Trick Room",
		}}, {
		ability: "Heatproof",
		item:    "Lum Berry",
		species: "Bronzong",
		moves: [4]string{"Dream Eater",
			"Hypnosis",
			"Signal Beam",
			"Trick Room",
		}}, {
		ability: "Heatproof",
		item:    "Leftovers",
		species: "Bronzong",
		moves: [4]string{"Psychic",
			"Shadow Ball",
			"Charge Beam",
			"Signal Beam",
		}}, {
		ability: "Heatproof",
		item:    "Quick Claw",
		species: "Bronzong",
		moves: [4]string{"Zen Headbutt",
			"Iron Head",
			"Earthquake",
			"Explosion",
		}}, {
		ability: "Sand Veil",
		item:    "Bright Powder",
		species: "Garchomp",
		moves: [4]string{"Dragon Claw",
			"Earthquake",
			"Double Team",
			"Sandstorm",
		}}, {
		ability: "Sand Veil",
		item:    "White Herb",
		species: "Garchomp",
		moves: [4]string{"Draco Meteor",
			"Earth Power",
			"Flamethrower",
			"Surf",
		}}, {
		ability: "Sand Veil",
		item:    "Focus Sash",
		species: "Garchomp",
		moves: [4]string{"Dragon Rush",
			"Stone Edge",
			"Aqua Tail",
			"Aerial Ace",
		}}, {
		ability: "Sand Veil",
		item:    "Persim Berry",
		species: "Garchomp",
		moves: [4]string{"Outrage",
			"Earthquake",
			"Crunch",
			"Fire Fang",
		}}, {
		ability: "Inner Focus",
		item:    "Bright Powder",
		species: "Lucario",
		moves: [4]string{"Aura Sphere",
			"Flash Cannon",
			"Water Pulse",
			"Roar",
		}}, {
		ability: "Inner Focus",
		item:    "Scope Lens",
		species: "Lucario",
		moves: [4]string{"Cross Chop",
			"Stone Edge",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Inner Focus",
		item:    "Muscle Band",
		species: "Lucario",
		moves: [4]string{"Close Combat",
			"Earthquake",
			"Blaze Kick",
			"Shadow Claw",
		}}, {
		ability: "Inner Focus",
		item:    "Expert Belt",
		species: "Lucario",
		moves: [4]string{"Aura Sphere",
			"Psychic",
			"Shadow Ball",
			"Dragon Pulse",
		}}, {
		ability: "Sand Stream",
		item:    "Persim Berry",
		species: "Hippowdon",
		moves: [4]string{"Earthquake",
			"Crunch",
			"Slack Off",
			"Curse",
		}}, {
		ability: "Sand Stream",
		item:    "Sitrus Berry",
		species: "Hippowdon",
		moves: [4]string{"Earthquake",
			"Swagger",
			"Sand Tomb",
			"Yawn",
		}}, {
		ability: "Sand Stream",
		item:    "White Herb",
		species: "Hippowdon",
		moves: [4]string{"Superpower",
			"Fire Fang",
			"Ice Fang",
			"Fissure",
		}}, {
		ability: "Sand Stream",
		item:    "Quick Claw",
		species: "Hippowdon",
		moves: [4]string{"Earthquake",
			"Stone Edge",
			"Crunch",
			"Thunder Fang",
		}}, {
		ability: "Sniper",
		item:    "Lum Berry",
		species: "Drapion",
		moves: [4]string{"Poison Jab",
			"Crunch",
			"Aqua Tail",
			"Acupressure",
		}}, {
		ability: "Sniper",
		item:    "Iron Ball",
		species: "Drapion",
		moves: [4]string{"Payback",
			"Poison Jab",
			"Fling",
			"Knock Off",
		}}, {
		ability: "Sniper",
		item:    "Scope Lens",
		species: "Drapion",
		moves: [4]string{"Cross Poison",
			"Fire Fang",
			"Thunder Fang",
			"Ice Fang",
		}}, {
		ability: "Sniper",
		item:    "Razor Claw",
		species: "Drapion",
		moves: [4]string{"Cross Poison",
			"Night Slash",
			"Earthquake",
			"Aerial Ace",
		}}, {
		ability: "Dry Skin",
		item:    "Black Sludge",
		species: "Toxicroak",
		moves: [4]string{"Poison Jab",
			"Brick Break",
			"X-Scissor",
			"Knock Off",
		}}, {
		ability: "Dry Skin",
		item:    "Wide Lens",
		species: "Toxicroak",
		moves: [4]string{"Dynamic Punch",
			"Poison Jab",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Dry Skin",
		item:    "Wise Glasses",
		species: "Toxicroak",
		moves: [4]string{"Sludge Bomb",
			"Focus Blast",
			"Shadow Ball",
			"Dark Pulse",
		}}, {
		ability: "Dry Skin",
		item:    "Razor Claw",
		species: "Toxicroak",
		moves: [4]string{"Gunk Shot",
			"Cross Chop",
			"Earthquake",
			"Stone Edge",
		}}, {
		ability: "Snow Warning",
		item:    "Lum Berry",
		species: "Abomasnow",
		moves: [4]string{"Giga Drain",
			"Ice Beam",
			"Water Pulse",
			"Grass Whistle",
		}}, {
		ability: "Snow Warning",
		item:    "Big Root",
		species: "Abomasnow",
		moves: [4]string{"Giga Drain",
			"Sheer Cold",
			"Ingrain",
			"Leech Seed",
		}}, {
		ability: "Snow Warning",
		item:    "Occa Berry",
		species: "Abomasnow",
		moves: [4]string{"Energy Ball",
			"Blizzard",
			"Shadow Ball",
			"Focus Blast",
		}}, {
		ability: "Snow Warning",
		item:    "Shell Bell",
		species: "Abomasnow",
		moves: [4]string{"Wood Hammer",
			"Avalanche",
			"Earthquake",
			"Rock Slide",
		}}, {
		ability: "Pressure",
		item:    "Chople Berry",
		species: "Weavile",
		moves: [4]string{"Night Slash",
			"Ice Punch",
			"Screech",
			"Fake Out",
		}}, {
		ability: "Pressure",
		item:    "Bright Powder",
		species: "Weavile",
		moves: [4]string{"Night Slash",
			"Attract",
			"Double Team",
			"Hail",
		}}, {
		ability: "Pressure",
		item:    "Focus Sash",
		species: "Weavile",
		moves: [4]string{"Night Slash",
			"X-Scissor",
			"Metal Claw",
			"Counter",
		}}, {
		ability: "Pressure",
		item:    "Razor Claw",
		species: "Weavile",
		moves: [4]string{"Night Slash",
			"Ice Punch",
			"Aerial Ace",
			"Brick Break",
		}}, {
		ability: "Sturdy",
		item:    "Light Clay",
		species: "Magnezone",
		moves: [4]string{"Thunderbolt",
			"Mirror Shot",
			"Light Screen",
			"Reflect",
		}}, {
		ability: "Sturdy",
		item:    "Lum Berry",
		species: "Magnezone",
		moves: [4]string{"Iron Head",
			"Explosion",
			"Swagger",
			"Psych Up",
		}}, {
		ability: "Sturdy",
		item:    "Chesto Berry",
		species: "Magnezone",
		moves: [4]string{"Charge Beam",
			"Flash Cannon",
			"Magnet Rise",
			"Thunder Wave",
		}}, {
		ability: "Sturdy",
		item:    "Bright Powder",
		species: "Magnezone",
		moves: [4]string{"Thunderbolt",
			"Flash Cannon",
			"Tri Attack",
			"Signal Beam",
		}}, {
		ability: "Oblivious",
		item:    "Chesto Berry",
		species: "Lickilicky",
		moves: [4]string{"Return",
			"Earthquake",
			"Belly Drum",
			"Rest",
		}}, {
		ability: "Oblivious",
		item:    "Expert Belt",
		species: "Lickilicky",
		moves: [4]string{"Surf",
			"Ice Beam",
			"Thunderbolt",
			"Shadow Ball",
		}}, {
		ability: "Oblivious",
		item:    "Lum Berry",
		species: "Lickilicky",
		moves: [4]string{"Return",
			"Gyro Ball",
			"Curse",
			"Rest",
		}}, {
		ability: "Oblivious",
		item:    "Lax Incense",
		species: "Lickilicky",
		moves: [4]string{"Body Slam",
			"Power Whip",
			"Earthquake",
			"Explosion",
		}}, {
		ability: "Solid Rock",
		item:    "Focus Band",
		species: "Rhyperior",
		moves: [4]string{"Rock Wrecker",
			"Earthquake",
			"Crunch",
			"Roar",
		}}, {
		ability: "Solid Rock",
		item:    "Expert Belt",
		species: "Rhyperior",
		moves: [4]string{"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
			"Aqua Tail",
		}}, {
		ability: "Solid Rock",
		item:    "Focus Sash",
		species: "Rhyperior",
		moves: [4]string{"Horn Drill",
			"Avalanche",
			"Payback",
			"Counter",
		}}, {
		ability: "Solid Rock",
		item:    "Choice Band",
		species: "Rhyperior",
		moves: [4]string{"Rock Wrecker",
			"Earthquake",
			"Hammer Arm",
			"Megahorn",
		}}, {
		ability: "Leaf Guard",
		item:    "Coba Berry",
		species: "Tangrowth",
		moves: [4]string{"Energy Ball",
			"Sludge Bomb",
			"Focus Blast",
			"Sleep Powder",
		}}, {
		ability: "Leaf Guard",
		item:    "Big Root",
		species: "Tangrowth",
		moves: [4]string{"Giga Drain",
			"Leech Seed",
			"Toxic",
			"Double Team",
		}}, {
		ability: "Leaf Guard",
		item:    "Heat Rock",
		species: "Tangrowth",
		moves: [4]string{"Solar Beam",
			"Wring Out",
			"Synthesis",
			"Sunny Day",
		}}, {
		ability: "Leaf Guard",
		item:    "Lax Incense",
		species: "Tangrowth",
		moves: [4]string{"Power Whip",
			"Earthquake",
			"Aerial Ace",
			"Brick Break",
		}}, {
		ability: "Motor Drive",
		item:    "Scope Lens",
		species: "Electivire",
		moves: [4]string{"Thunder Punch",
			"Cross Chop",
			"Thunder Wave",
			"Screech",
		}}, {
		ability: "Motor Drive",
		item:    "Wide Lens",
		species: "Electivire",
		moves: [4]string{"Thunder",
			"Dynamic Punch",
			"Rock Slide",
			"Iron Tail",
		}}, {
		ability: "Motor Drive",
		item:    "Wise Glasses",
		species: "Electivire",
		moves: [4]string{"Thunderbolt",
			"Psychic",
			"Focus Blast",
			"Signal Beam",
		}}, {
		ability: "Motor Drive",
		item:    "Shuca Berry",
		species: "Electivire",
		moves: [4]string{"Thunder Punch",
			"Fire Punch",
			"Ice Punch",
			"Earthquake",
		}}, {
		ability: "Flame Body",
		item:    "Heat Rock",
		species: "Magmortar",
		moves: [4]string{"Fire Blast",
			"Focus Blast",
			"Will-O-Wisp",
			"Sunny Day",
		}}, {
		ability: "Flame Body",
		item:    "Shuca Berry",
		species: "Magmortar",
		moves: [4]string{"Fire Punch",
			"Focus Punch",
			"Confuse Ray",
			"SmokeScreen",
		}}, {
		ability: "Flame Body",
		item:    "Passho Berry",
		species: "Magmortar",
		moves: [4]string{"Flare Blitz",
			"Thunder Punch",
			"Earthquake",
			"Brick Break",
		}}, {
		ability: "Flame Body",
		item:    "White Herb",
		species: "Magmortar",
		moves: [4]string{"Overheat",
			"Psychic",
			"Focus Blast",
			"Confuse Ray",
		}}, {
		ability: "Serene Grace",
		item:    "Power Herb",
		species: "Togekiss",
		moves: [4]string{"Sky Attack",
			"Extreme Speed",
			"Drain Punch",
			"Roost",
		}}, {
		ability: "Serene Grace",
		item:    "Scope Lens",
		species: "Togekiss",
		moves: [4]string{"Air Slash",
			"Ominous Wind",
			"Silver Wind",
			"Ancient Power",
		}}, {
		ability: "Serene Grace",
		item:    "Wise Glasses",
		species: "Togekiss",
		moves: [4]string{"Air Slash",
			"Heat Wave",
			"Signal Beam",
			"Magical Leaf",
		}}, {
		ability: "Serene Grace",
		item:    "Expert Belt",
		species: "Togekiss",
		moves: [4]string{"Hyper Beam",
			"Air Slash",
			"Aura Sphere",
			"Psychic",
		}}, {
		ability: "Tinted Lens",
		item:    "Coba Berry",
		species: "Yanmega",
		moves: [4]string{"Signal Beam",
			"Air Cutter",
			"Detect",
			"Double Team",
		}}, {
		ability: "Tinted Lens",
		item:    "Muscle Band",
		species: "Yanmega",
		moves: [4]string{"Aerial Ace",
			"U-turn",
			"Night Slash",
			"Steel Wing",
		}}, {
		ability: "Tinted Lens",
		item:    "Lum Berry",
		species: "Yanmega",
		moves: [4]string{"Silver Wind",
			"Ancient Power",
			"Ominous Wind",
			"Giga Drain",
		}}, {
		ability: "Tinted Lens",
		item:    "Wise Glasses",
		species: "Yanmega",
		moves: [4]string{"Bug Buzz",
			"Air Slash",
			"Psychic",
			"Shadow Ball",
		}}, {
		ability: "Leaf Guard",
		item:    "Scope Lens",
		species: "Leafeon",
		moves: [4]string{"Leaf Blade",
			"Aerial Ace",
			"Double Team",
			"Baton Pass",
		}}, {
		ability: "Leaf Guard",
		item:    "Bright Powder",
		species: "Leafeon",
		moves: [4]string{"Leaf Blade",
			"Last Resort",
			"Curse",
			"Grass Whistle",
		}}, {
		ability: "Leaf Guard",
		item:    "Heat Rock",
		species: "Leafeon",
		moves: [4]string{"Leaf Blade",
			"X-Scissor",
			"Synthesis",
			"Sunny Day",
		}}, {
		ability: "Leaf Guard",
		item:    "Quick Claw",
		species: "Leafeon",
		moves: [4]string{"Leaf Blade",
			"X-Scissor",
			"Aerial Ace",
			"Bite",
		}}, {
		ability: "Snow Cloak",
		item:    "Lax Incense",
		species: "Glaceon",
		moves: [4]string{"Ice Beam",
			"Water Pulse",
			"Double Team",
			"Baton Pass",
		}}, {
		ability: "Snow Cloak",
		item:    "Leftovers",
		species: "Glaceon",
		moves: [4]string{"Ice Beam",
			"Double Team",
			"Yawn",
			"Hail",
		}}, {
		ability: "Snow Cloak",
		item:    "Focus Sash",
		species: "Glaceon",
		moves: [4]string{"Blizzard",
			"Hyper Beam",
			"Hail",
			"Mirror Coat",
		}}, {
		ability: "Snow Cloak",
		item:    "Wise Glasses",
		species: "Glaceon",
		moves: [4]string{"Ice Beam",
			"Shadow Ball",
			"Signal Beam",
			"Water Pulse",
		}}, {
		ability: "Sand Veil",
		item:    "Yache Berry",
		species: "Gliscor",
		moves: [4]string{"Earthquake",
			"Aerial Ace",
			"Swords Dance",
			"Baton Pass",
		}}, {
		ability: "Sand Veil",
		item:    "Razor Fang",
		species: "Gliscor",
		moves: [4]string{"Earthquake",
			"Fire Fang",
			"Thunder Fang",
			"Ice Fang",
		}}, {
		ability: "Sand Veil",
		item:    "Focus Sash",
		species: "Gliscor",
		moves: [4]string{"Guillotine",
			"Earthquake",
			"U-turn",
			"Counter",
		}}, {
		ability: "Sand Veil",
		item:    "Expert Belt",
		species: "Gliscor",
		moves: [4]string{"Earthquake",
			"Aerial Ace",
			"X-Scissor",
			"Stone Edge",
		}}, {
		ability: "Snow Cloak",
		item:    "Icy Rock",
		species: "Mamoswine",
		moves: [4]string{"Earthquake",
			"Ice Fang",
			"Peck",
			"Hail",
		}}, {
		ability: "Snow Cloak",
		item:    "Sitrus Berry",
		species: "Mamoswine",
		moves: [4]string{"Avalanche",
			"Earthquake",
			"Iron Head",
			"Curse",
		}}, {
		ability: "Snow Cloak",
		item:    "Lax Incense",
		species: "Mamoswine",
		moves: [4]string{"Earthquake",
			"Superpower",
			"Fissure",
			"Hail",
		}}, {
		ability: "Snow Cloak",
		item:    "Life Orb",
		species: "Mamoswine",
		moves: [4]string{"Earthquake",
			"Ice Fang",
			"Stone Edge",
			"Double-Edge",
		}}, {
		ability: "Download",
		item:    "Sitrus Berry",
		species: "PorygonZ",
		moves: [4]string{"Tri Attack",
			"Shadow Ball",
			"Recycle",
			"Conversion 2",
		}}, {
		ability: "Download",
		item:    "Choice Scarf",
		species: "PorygonZ",
		moves: [4]string{"Tri Attack",
			"Thunder Wave",
			"Recover",
			"Trick",
		}}, {
		ability: "Download",
		item:    "Wise Glasses",
		species: "PorygonZ",
		moves: [4]string{"Psychic",
			"Ice Beam",
			"Signal Beam",
			"Charge Beam",
		}}, {
		ability: "Download",
		item:    "Expert Belt",
		species: "PorygonZ",
		moves: [4]string{"Tri Attack",
			"Shadow Ball",
			"Thunderbolt",
			"Recover",
		}}, {
		ability: "Steadfast",
		item:    "Kasib Berry",
		species: "Gallade",
		moves: [4]string{"Zen Headbutt",
			"Brick Break",
			"Thunder Wave",
			"Confuse Ray",
		}}, {
		ability: "Steadfast",
		item:    "Bright Powder",
		species: "Gallade",
		moves: [4]string{"Drain Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Steadfast",
		item:    "Scope Lens",
		species: "Gallade",
		moves: [4]string{"Psycho Cut",
			"Stone Edge",
			"Aerial Ace",
			"X-Scissor",
		}}, {
		ability: "Steadfast",
		item:    "Scope Lens",
		species: "Gallade",
		moves: [4]string{"Psycho Cut",
			"Close Combat",
			"Leaf Blade",
			"Night Slash",
		}}, {
		ability: "Magnet Pull",
		item:    "Cheri Berry",
		species: "Probopass",
		moves: [4]string{"Ancient Power",
			"Magnet Bomb",
			"Thunder Wave",
			"Protect",
		}}, {
		ability: "Magnet Pull",
		item:    "Chople Berry",
		species: "Probopass",
		moves: [4]string{"Iron Head",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Magnet Pull",
		item:    "Scope Lens",
		species: "Probopass",
		moves: [4]string{"Stone Edge",
			"Iron Head",
			"Earthquake",
			"Explosion",
		}}, {
		ability: "Magnet Pull",
		item:    "Life Orb",
		species: "Probopass",
		moves: [4]string{"Flash Cannon",
			"Power Gem",
			"Earth Power",
			"Thunderbolt",
		}}, {
		ability: "Pressure",
		item:    "Iron Ball",
		species: "Dusknoir",
		moves: [4]string{"Shadow Punch",
			"Fling",
			"Will-O-Wisp",
			"Trick Room",
		}}, {
		ability: "Pressure",
		item:    "Leftovers",
		species: "Dusknoir",
		moves: [4]string{"Curse",
			"Pain Split",
			"Confuse Ray",
			"Attract",
		}}, {
		ability: "Pressure",
		item:    "Scope Lens",
		species: "Dusknoir",
		moves: [4]string{"Shadow Punch",
			"Fire Punch",
			"Thunder Punch",
			"Ice Punch",
		}}, {
		ability: "Pressure",
		item:    "Muscle Band",
		species: "Dusknoir",
		moves: [4]string{"Shadow Punch",
			"Earthquake",
			"Brick Break",
			"Rock Slide",
		}}, {
		ability: "Snow Cloak",
		item:    "Cheri Berry",
		species: "Froslass",
		moves: [4]string{"Ice Beam",
			"Ominous Wind",
			"Confuse Ray",
			"Attract",
		}}, {
		ability: "Snow Cloak",
		item:    "Focus Band",
		species: "Froslass",
		moves: [4]string{"Ice Punch",
			"Sucker Punch",
			"Swagger",
			"Psych Up",
		}}, {
		ability: "Snow Cloak",
		item:    "Expert Belt",
		species: "Froslass",
		moves: [4]string{"Ice Beam",
			"Thunderbolt",
			"Signal Beam",
			"Destiny Bond",
		}}, {
		ability: "Snow Cloak",
		item:    "Lax Incense",
		species: "Froslass",
		moves: [4]string{"Blizzard",
			"Shadow Ball",
			"Psychic",
			"Hail",
		}},
}
